name: example
max_steps: 1000

agent:
  name: base

  batch_size: 32

  actor:
    name: Percentile
    num_samples: 128
    actor_percentile: 0.1
    proposal_percentile: 0.2
    uniform_weight: 1.0
    actor_lr: 0.001
    proposal_lr: 0.001
    max_action_stddev: 1.0

  critic:
    name: QRC
    stepsize: 0.001
    ensemble: 1
    ensemble_prob: 1.0
    num_rand_actions : 1
    action_regularization: 0.0
    l2_regularization: 1.0

env:
  name: Saturation-v0
