defaults:
  - base: fc
  - _self_

dist : beta
head_layer_init : Xavier
head_activation : [
  [{"name": "softplus"}, {"name": "bias", "args": [1]}],
  [
    {
      "name": "tanh_shift",
      "kwargs": {"shift": -4, "denom": 1, "high": 10000, "low": 1}
    }
  ]
]
head_bias : True
