defaults:
  - base: fc
  - _self_

dist : gamma
head_layer_init : Xavier
head_activation : [
  # Since policies should always return actions in [0, 1], we can force the
  # mean to stay within this range
  [{"name": "softplus"}, {"name": "bias", "args": [1]}],
  [{"name": "softplus"}, {"name": "bias", "args": [1]}],
]
head_bias : True
