defaults:
  - base: fc
  - _self_

dist : laplace
head_layer_init : Xavier
head_activation : [
  # Since policies should always return actions in [0, 1], we can force the
  # mean to stay within this range
  [{"name": "functional", "args": ["sigmoid"]}],

  [{"name": "clamp", "args": [-20, 2]}, {"name": "exp"}]
]
head_bias : True
