defaults:
  - base: fc
  - _self_

dist : squashed_gaussian
head_layer_init : Xavier
head_activation : [
  [{"name": "identity"}],
  [{"name": "clamp", "args": [-20, 2]}, {"name": "exp"}]
]
head_bias : True
