  batch_size: 512
  memory: 100000
  name: sql_buffer
  device : cpu
  # seed : ${experiment.seed}
  seed : 0
  con_cfg:  
    username: "eng"
    password: "rlcore"
    ip: "10.123.10.55"
    port: 3306