[project]
name = 'research-template'
version = '0.0.0'
description = 'A repo to test agent ideas'
authors = []
requires-python = ">=3.13"
readme = 'README.md'
dependencies = [
    'chex~=0.1',
    "distrax~=0.1",
    "gymnasium~=1.0",
    'jax~=0.5',
    "matplotlib~=3.10",
    "numba~=0.61",
    'numpy~=2.1',
    'optax~=0.2',
    "pydantic~=2.10",
    "tqdm~=4.67",
]

[dependency-groups]
dev = [
    'commitizen>=4.4.1',
    'pip>=25.0',
    'pre-commit>=4.2.0',
    'pyright>=1.1.397',
    'pytest>=8.3.5',
    'ruff>=0.11.2',
    'uv>=0.6.9',
]

[tool]
[tool.commitizen]
name = "cz_conventional_commits"
version_scheme = "pep440"
version_provider = "pep621"
update_changelog_on_bump = true
major_version_zero = true

[tool.pyright]
include = ['.']
exclude = [
    '.venv/',
]
venvPath = '.'
venv = '.venv'
typeCheckingMode = 'standard'

# common overrides
useLibraryCodeForTypes = true
strictListInference = true
strictDictionaryInference = true
strictSetInference = true
enableReachabilityAnalysis = true

# stricter overrides
reportInconsistentConstructor = true
reportMissingParameterType = true
reportUnnecessaryCast = true
reportUnnecessaryIsInstance = true
reportUnusedClass = true
reportUnusedExpression = true
reportUnusedFunction = true

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ['F', 'E', 'W', 'B', 'I']
ignore = [
    'E402',

    # multiple statements on one line. Incompatible with:
    # if cond: break
    'E701',

    # syntax error in forward declaration - incompatible with jaxtyping
    'F722',
]

[tool.ruff.format]
quote-style = "double"

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
asyncio_mode = "auto"
