name: example
max_steps: 5000

agent:
  name: base

  num_samples: 128
  actor_percentile: 0.1
  proposal_percentile: 0.2
  uniform_weight: 1.0
  batch_size: 256

  actor_lr: 0.001
  proposal_lr: 0.001

  critic:
    name: QRC
    stepsize: 0.001
    ensemble: 1
    ensemble_prob: 1.0
    batch_size: 256
    num_rand_actions : 1
    action_regularization: 0.0

env:
  name: Saturation-v0
