name: example
max_steps: 5000
nominal_setpoint: 0.5

action_bounds:
  delta: True
  delta_lo: 0.1
  delta_hi: 0.1

agent:
  name: gac

  batch_size: 32 # not the same as prod

  actor:
    name: Percentile
    num_samples: 128
    actor_percentile: 0.05
    proposal_percentile: 0.2
    uniform_weight: 0.84 # (1-prop_percentile_learned*policy.proposal_percentile) = 1-.8*.2
    actor_lr: 0.0001
    proposal_lr: 0.0001
    sort_noise: 0.0

  critic:
    name: QRC
    stepsize: 0.0001
    ensemble: 1
    ensemble_prob: 1.0
    num_rand_actions : 10
    action_regularization: 0.0001
    l2_regularization: 1.0
    action_regularization_epsilon: 0.1

env:
  name: Saturation-v0
