defaults:
  - base
  - override /state_constructor: multi_trace
  - _self_

name : anytime

buffer:
  batch_size: 256
  memory: 100000
  name: uniform
  device: cpu
  seed: ${experiment.seed}

train_itr: 1000
batch_size : 256
interpolation : linear

model:
  layer_norm: 0
  arch: [256, 256]
  init_args: ReLU
  head_activation: None
  activation: ReLU
  layer_init: Xavier
  bias: True
  name: fc

optimizer:
  lr: 0.0001
  weight_decay: 0.0
  name: adam