defaults:
  - /state_constructor: multi_trace
  - _self_

endo_inds : [0] # indices of endogenous variables within the observation
exo_inds : [1] # indices of exogenous variables within the observation
max_rollout_len : 180
steps_per_decision : ${interaction.steps_per_decision}
num_test_rollouts : 20
gamma : ${experiment.gamma}