name : gru

train_itr: 100
batch_size : 64

endo_inds : [0] # indices of endogenous variables within the observation
exo_inds : [1] # indices of exogenous variables within the observation

model:
  base:
    layer_norm: 0
    arch: [64, 64]
    init_args: ReLU
    head_activation: None
    activation: ReLU
    layer_init: Xavier
    bias: True
    name: fc
  gru_hidden_dim : 256
  num_gru_layers : 1

optimizer:
  lr: 0.0001
  weight_decay: 0.0
  name: adam

max_rollout_len : ${data_loader.trajectory_len}
steps_per_decision : ${interaction.steps_per_decision}
warmup_len : 180
skip : 5