name : gru

train_itr: 2000
batch_size : 128

endo_inds : [0] # indices of endogenous variables within the observation
exo_inds : [1] # indices of exogenous variables within the observation

model:
  base:
    layer_norm: 0
    arch: [32, 32]
    init_args: ReLU
    head_activation: None
    activation: ReLU
    layer_init: Xavier
    bias: True
    name: fc
  gru_hidden_dim : 32
  num_gru_layers : 2
  gru_input_dim : 4

optimizer:
  lr: 0.0001
  weight_decay: 0.0
  name: adam

max_rollout_len : 480
steps_per_decision : ${interaction.steps_per_decision}
warmup_len : 300
skip : 1