defaults:
  - /state_constructor: multi_trace
  - base
  - _self_

name : knn

buffer:
  batch_size: 256
  memory: 100000
  name: uniform
  device: cpu
  seed: ${experiment.seed}

train_itr: 1000
batch_size : 256

endo_inds : [0] # indices of endogenous variables within the observation
exo_inds : [1] # indices of exogenous variables within the observation

model:
  layer_norm: 0
  arch: [256, 256]
  init_args: ReLU
  head_activation: None
  activation: ReLU
  layer_init: Xavier
  bias: True
  name: fc

optimizer:
  lr: 0.0001
  weight_decay: 0.0
  name: adam

max_rollout_len : 180
steps_per_decision : ${interaction.steps_per_decision}
num_test_rollouts : 20
learn_metric : True
include_actions : False
output_dim : 10
num_neighbors : 3
beta : 0.5
zeta : 0.5
