name : nstep

train_itr: 1000
batch_size : 32

endo_inds : [0] # indices of endogenous variables within the observation
exo_inds : [1] # indices of exogenous variables within the observation

model:
  base:
  layer_norm: 0
  arch: [256, 256]
  init_args: ReLU
  head_activation: None
  activation: ReLU
  layer_init: Xavier
  bias: True
  name: fc

optimizer:
  lr: 0.001
  weight_decay: 0.0
  name: adam

max_rollout_len : 180
steps_per_decision : ${interaction.steps_per_decision}
warmup_len : 0
skip : 1