name : simple

buffer:
  batch_size: 16
  memory: 100000
  name: uniform
  device: cpu
  seed: ${experiment.seed}

train_itr: 10000
batch_size : 64

model:
  layer_norm: 0
  arch: [ 256, 256]
  init_args: ReLU
  head_activation: None
  activation: ReLU
  layer_init: Xavier
  bias: True
  name: fc

optimizer:
  lr: 0.00001
  weight_decay: 0.0
  name: adam

max_rollout_len : ${data_loader.trajectory_len}
steps_per_decision : ${interaction.steps_per_decision}