defaults:
  - /state_constructor: multi_trace
  - _self_

name : simple

buffer:
  batch_size: 64
  memory: 100000
  name: uniform
  device: cpu
  seed: ${experiment.seed}


train_itr: 10000
batch_size : 64

endo_inds : [0] # indices of endogenous variables within the observation
exo_inds : [1] # indices of exogenous variables within the observation

model:
  layer_norm: 0
  arch: [256, 256]
  init_args: ReLU
  head_activation: None
  activation: ReLU
  layer_init: Xavier
  bias: True
  name: fc

optimizer:
  lr: 0.0001
  weight_decay: 0.0
  name: adam

max_rollout_len : 400
steps_per_decision : ${interaction.steps_per_decision}
num_test_rollouts : 20