#NOTE: do not add your credentials here
# 1) make a new credentials_local.yaml and add your credentials there
# 2) do not commit that file
# 3) set default: db: credentials_local in the config.yaml (or whichever config you're using)
# username: "grafana"
# password: "a1b2c3d4"
# ip: "127.0.0.1"
username: "eng"
password: "rlcore"
ip: "10.123.10.55"
port: 3306