name : lso
init_step_size : 0.1
max_backtracking_steps: 30
unit_norm_direction: False
fallback_step_size: 0.0001
optim:
  name: "Adam"
  args: []
  kwargs: {}

init:
  name: "To"
  stepsize: 0.001

search_condition:
  name: "Armijo"
  c: 0.1
  beta: 0.9
  min_step_size: 0
  max_step_size: 1
