defaults:
  - base_agent
  - critic: critic
  - actor : network
  - _self_

buffer :
  batch_size: 512
  memory: 100000
  name: Uniform
  device : cpu
  seed : ${experiment.seed}

name : SimpleAC
tau : 0.0
device : ${experiment.device}

