defaults:
  - base: fc
  - _self_

ensemble : 10 # ${alerts.base.ensemble}
name : ensemble
reduct :
  name: mean # ${alerts.base.reduct}
bootstrap_reduct :
  name: mean
policy_reduct :
  name: mean
vmap : False
