name : direct_action
offline_data_path : offline_data
train_filenames : []
test_filenames : []
skip_rows : 1 # Number of lines to skip at the top of the csv file
header : 0 # df_col_names replaces the column names in the csv file
df_col_names : []
obs_col_names: []
action_col_names : []
date_col_name : Date
max_time_delta: 10 # In seconds
obs_length : 60

