defaults:
  - critic_network: ensemble
  - critic_optimizer : custom_adam
  -  _self_

name : ${agent.critic.critic_network.name}_linesearch # Revan: this works for getting the networks name, but isn't the fanciest
polyak : 0.0
target_sync_freq : 1