line-length = 120

[lint]
select = [
    'F', # flake8
    'E', # errors
    'W', # warnings
    'B', # bugbear
    'I', # isort
    'COM', # flake8-commas
    'C4', # flake8-comprehensions
    'PIE', # flake8-pie

]
ignore = [
    'E402',

    # multiple statements on one line. Incompatible with:
    # if cond: break
    'E701',

    # syntax error in forward declaration - incompatible with jaxtyping
    'F722',
]

[format]
quote-style = "double"
