defaults:
  - base_gym_env
  - _self_

name : four_rooms
discrete_control : False
action_scale: 0.01
noise_scale: 0.0

decay_scale: 1.0
decay_probability: 0.0
misleading_reward: True

# decay_scale: 0.25
# decay_probability: 1.0
# misleading_reward: False
