defaults:
  - base_env
  - _self_

reward_high : -0.4
reward_low : -0.7

name : MountainCarContinuous-v0
discrete_control : False

environment:
  type: gym.make
  args:
    - MountainCarContinuous-v0
  kwargs:
    render_mode: human
    goal_velocity: 0.1
