defaults:
  - base_env
  - reward : reseau
  - _self_

name: Reseau_online
db_settings_pth: "\\Users\\RLCORE\\corerl\\control\\src\\environment\\reseau\\db_settings_osoyoos.json"
opc_settings_pth : "\\Users\\RLCORE\\corerl\\control\\src\\environment\\reseau\\opc_settings_osoyoos.json"
control_tags_online : ["osoyoos.plc.Process_DB.P250 Flow Pace Calc.Flow Pace Multiplier"]
control_tags_default : 20.0
col_names : ["ait301_pv", "fit250_pv",  "p250_fp"]
reset_fpm: 15
decision_freq : 1800
obs_freq : 60
obs_window : 60
last_n_obs : 60
obs_space_low : [250.0, 0.0, 0.0]
obs_space_high : [450.0, 20.0, 300.0]
orp_sp : 350.0
penalty_weight : 10.0
discrete_control : False
change_action : False