name: Reseau_online
db_settings_pth: "\\Users\\RLCORE\\corerl\\control\\src\\environment\\reseau\\db_settings_osoyoos.json"
opc_settings_pth : "\\Users\\RLCORE\\corerl\\control\\src\\environment\\reseau\\opc_settings_osoyoos.json"
control_tags : ["osoyoos.plc.Process_DB.P250 Flow Pace Calc.Flow Pace Multiplier"]
reset_fpm: 15
col_names : [
            "ait101_pv",
            "ait301_pv",
            "ait401_pv",
            "fit101_pv",
            "fit210_pv",
            "fit230_pv",
            "fit250_pv",
            "fit401_pv",
            "p250_fp",
            "pt100_pv",
            "pt101_pv",
            "pt161_pv"
        ]

