defaults:
  - base_env
  - reward : reseau
  - _self_

opc:
  ip_address : "localhost"
  port : "49320"
  conn_stats : False

db:
  bucket : "rlcore-bucket"
  org : "rlcore"
  url :  "http://localhost:8086"
  token : "placeholder_token"


name: reseau
control_tags : ["osoyoos.plc.Process_DB.P250 Flow Pace Calc.Flow Pace Multiplier"]
col_names : ["ait301_pv", "fit250_pv", "p250_fp"]
action_names : ["p250_fp"]
obs_col_names : ["ait301_pv", "fit250_pv"]
endo_obs_col_names : ["ait301_pv"]
endo_inds : [0]
action_low : 0
action_high : 300

obs_space_low :  [297, -1.8084491e-02]
obs_space_high :  [470,  80]
discrete_control : False

reward_high : 4
reward_low : -9
reward_bias : 4