defaults:
  - base_env
  - reward : reseau
  - _self_

opc:
  ip_address : "localhost"
  port : "49320"
  conn_stats : False

db:
  bucket : "rlcore-bucket"
  org : "rlcore"
  url :  "http://localhost:8086"
  token : "placeholder_token"


name: reseau
control_tags : ["osoyoos.plc.Process_DB.P250 Flow Pace Calc.Flow Pace Multiplier"]
col_names : ["ait301_pv", "fit250_pv", "p250_fp"]
action_low : 0
action_high : 300

obs_space_low : [250.0, 0.0]
obs_space_high : [450.0, 20.0]
discrete_control : False