defaults:
  - base_env
  - _self_

name : three_tanks_v2
random_sp : [3]
lr_constrain : 0

discrete_control : False
change_action : True
constant_pid : False
delta_step : 0.1

reset_to_high_reward: True
reset_buffer_size: 1500
reset_buffer_add_delay: 0
reset_buffer_always_include_start: False
reset_temperature: 1
n_internal_iter: 500

baseline_scale: 1
mse_penalty_reward: true
