defaults:
  - env: env/saturation

interaction:
  name: sim_interaction
  obs_period: 00:00:01
  action_period: 00:00:01

experiment :
  exp_name : "saturation"
  max_steps : 10000

metrics:
  enabled: True

evals:
  enabled: True

pipeline:
  tags:
  # meta tags
  - name: reward
    type: meta

  - name: terminated
    type: meta

  - name: truncated
    type: meta

  # observations
  - name: tag-0
    operating_range: [0, 1]

  # actions
  - name: action-0
    type: ai_setpoint
    operating_range: [0, 0.5]
    action_bounds: ['{action-0}-0.1', '{action-0}+0.1']
    # action_bounds: ['{action-0}-0.5', '{action-0}+0.5']
