defaults:
  - env: env/multisaturation

interaction:
  name: sim_interaction
  obs_period: 00:00:01
  action_period: 00:00:01

experiment :
  exp_name : "saturation"
  max_steps : 10000

metrics:
  enabled: True

evals:
  enabled: True

agent:
  name: greedy_ac

  critic:
    critic_network:
      ensemble: 10

  policy:
    optimizer:
      lr : 0.0005

pipeline:
  state_constructor:
    defaults:
      - name: multi_trace
        trace_values: [0.0, 0.9, 0.95, 0.99]

  tags:
  # meta tags
  - name: reward
    preprocess:
    - name: identity
    reward_constructor:
    - name: identity
    state_constructor:
    - name: 'null'

  - name: terminated
    is_meta: True

  - name: truncated
    is_meta: True

  # observations
  - name: tag-0
    operating_range: [0, 1]
  - name: tag-1
    operating_range: [0, 1]
  - name: tag-2
    operating_range: [0, 1]

  # actions
  - name: action-0
    operating_range: [0, 0.5]
    action_bounds: ['{action-0}-0.1', '{action-0}+0.1']
    # action_bounds: ['{action-0}-0.5', '{action-0}+0.5']
    action_constructor:
      - name: identity

  - name: action-1
    operating_range: [0, 0.5]
    action_bounds: ['{action-1}-0.1', '{action-1}+0.1']
    # action_bounds: ['{action-1}-0.5', '{action-1}+0.5']
    action_constructor:
      - name: identity

  - name: action-2
    operating_range: [0, 0.5]
    action_bounds: ['{action-2}-0.1', '{action-2}+0.1']
    # action_bounds: ['{action-2}-0.5', '{action-2}+0.5']
    action_constructor:
      - name: identity
