pipeline:
  tags:
    - name: MyWriteableVariable
      type: ai_setpoint
      node_identifier: "ns=2;i=2"
      operating_range: [0, 10]

coreio:
  opc_conn_url: opc.tcp://admin@localhost:4840

interaction:
  name: dep_interaction
  restore_checkpoint: False
  historical_batch_size: 100
  setpoint_ping_period: 00:00:10
  hist_chunk_start: 2025-02-05 12:00:00+0000 # YYYY-MM-DD hh:mm:ss
  obs_period: 00:00:01
  action_period: 00:00:03
  update_period: 00:00:01
  state_age_tol: 00:00:01
  heartbeat:
    connection_id: f2365731-eeee-4b3f-b1dc-54634735d1d9
    heartbeat_node_id: "ns=2;s=heartbeat"
    heartbeat_period: 00:00:01
    max_counter: 10
