coreio:
  coreio_origin: "tcp://localhost:5557"
  opc_connections:
    - connection_id: asdxf
      opc_conn_url: opc.tcp://admin@localhost:4840

pipeline:
  tags:
    - name: MyWriteableVariable
      type: ai_setpoint
      # connection_id just has to be consistent with the one 
      # in coreio.opc_connections, it is not stored anywhere external
      connection_id: asdxf 
      node_identifier: "ns=2;i=2"
      operating_range: [0, 10]

interaction:
  name: dep_interaction
  restore_checkpoint: False
  historical_batch_size: 100
  setpoint_ping_period: 00:00:10
  obs_period: 00:00:01
  action_period: 00:00:03
  update_period: 00:00:01
  state_age_tol: 00:00:01
