coreio:
  coreio_origin: "tcp://localhost:5557"
  opc_connections:
    - connection_id: asdxf
      opc_conn_url: opc.tcp://admin@localhost:4840
      security_policy:
        policy: none
        mode: none
      authentication_mode: anonymous
  data_ingress:
    enabled: True
    ingress_period: 00:00:01
  tags:
    - name: MyWriteableVariable
      # connection_id just has to be consistent with the one 
      # in coreio.opc_connections, it is not stored anywhere external
      connection_id: asdxf 
      node_identifier: "ns=2;i=2"
      operating_range: [0, 10]

infra:
  db:
    drivername: postgresql+psycopg2
    username: postgres
    password: password
    ip: localhost
    port: 5432
    db_name: postgres

env:
  name: dep_async_env
  db:
    table_name: coreio_test


interaction:
  name: dep_interaction
  obs_period: 00:00:01
  action_period: 00:00:01
  heartbeat:
    connection_id: asdxf
    heartbeat_node_id: "ns=2;i=3"
