defaults:
  - _self_

deployment:
  python_executable: python
  python_entrypoint: main.py
  config_name: pendulum
  options: [experiment.max_steps=25]

event_bus:
  python_entrypoint: event_bus.py
  host: localhost
  port: 8123
