defaults:
  - env: env/distraction_world.yaml

interaction:
  name: sim_interaction
  obs_period: 00:00:01
  action_period: 00:00:01

experiment :
  exp_name : "distraction_world"
  max_steps: 5000
  gamma: 0


metrics:
  enabled: True

    
pipeline:
  tags:
  # meta tags
  - name: reward
    preprocess:
    - name: identity
    outlier:
      name: identity
    reward_constructor:
    - name: identity
    state_constructor:
    - name: 'null'
    preprocess:
    - name: identity

  - name: terminated
    preprocess:
    - name: identity
    is_meta: True
    outlier:
      name: identity

  - name: truncated
    preprocess:
    - name: identity
    is_meta: True
    outlier:
      name: identity


  - name: action-0
    agg: avg
    node_identifier: null
    is_meta: false
    is_endogenous: true
    operating_range:
    - -1.0
    - 1.0
    red_bounds: null
    yellow_bounds: null
    change_bounds: null
    outlier:
      name: identity
    imputer: null
    preprocess:
    - name: normalize
      min: null
      max: null
      from_data: false
    reward_constructor:
    - name: 'null'
    action_constructor:
    - name: identity
    filter: null

  - name: tag-0
    agg: avg
    node_identifier: null
    is_meta: false
    is_endogenous: true
    operating_range:
    - -1.0
    - 1.0
    red_bounds: null
    yellow_bounds: null
    change_bounds: null
    outlier:
      name: identity
    imputer:
      name: identity
    preprocess:
    - name: normalize
      min: null
      max: null
      from_data: false
    reward_constructor:
    - name: 'null'
    action_constructor: null
    state_constructor:
    - name: multi_trace
      trace_values:
      - 0.0

    filter: null
  - name: tag-1
    agg: avg
    node_identifier: null
    is_meta: false
    is_endogenous: true
    operating_range:
    - -1.0
    - 1.0
    red_bounds: null
    yellow_bounds: null
    change_bounds: null
    outlier:
      name: identity
    imputer:
      name: identity
    preprocess:
    - name: normalize
      min: null
      max: null
      from_data: false
    reward_constructor:
    - name: 'null'
    action_constructor: null
    state_constructor:
    - name: multi_trace
      trace_values:
      - 0.0

    filter: null
  - name: tag-2
    agg: avg
    node_identifier: null
    is_meta: false
    is_endogenous: true
    operating_range:
    - -1.0
    - 1.0
    red_bounds: null
    yellow_bounds: null
    change_bounds: null
    outlier:
      name: identity
    imputer:
      name: identity
    preprocess:
    - name: normalize
      min: null
      max: null
      from_data: false
    reward_constructor:
    - name: 'null'
    action_constructor: null
    state_constructor:
    - name: multi_trace
      trace_values:
      - 0.0

    filter: null
  - name: tag-3
    agg: avg
    node_identifier: null
    is_meta: false
    is_endogenous: true
    operating_range:
    - -1.0
    - 1.0
    red_bounds: null
    yellow_bounds: null
    change_bounds: null
    outlier:
      name: identity
    imputer:
      name: identity
    preprocess:
    - name: normalize
      min: null
      max: null
      from_data: false
    reward_constructor:
    - name: 'null'
    action_constructor: null
    state_constructor:
    - name: multi_trace
      trace_values:
      - 0.0

    filter: null
  - name: tag-4
    agg: avg
    node_identifier: null
    is_meta: false
    is_endogenous: true
    operating_range:
    - -1.0
    - 1.0
    red_bounds: null
    yellow_bounds: null
    change_bounds: null
    outlier:
      name: identity
    imputer:
      name: identity
    preprocess:
    - name: normalize
      min: null
      max: null
      from_data: false
    reward_constructor:
    - name: 'null'
    action_constructor: null
    state_constructor:
    - name: multi_trace
      trace_values:
      - 0.0

    filter: null
  - name: tag-5
    agg: avg
    node_identifier: null
    is_meta: false
    is_endogenous: true
    operating_range:
    - -1.0
    - 1.0
    red_bounds: null
    yellow_bounds: null
    change_bounds: null
    outlier:
      name: identity
    imputer:
      name: identity
    preprocess:
    - name: normalize
      min: null
      max: null
      from_data: false
    reward_constructor:
    - name: 'null'
    action_constructor: null
    state_constructor:
    - name: multi_trace
      trace_values:
      - 0.0

    filter: null
  - name: tag-6
    agg: avg
    node_identifier: null
    is_meta: false
    is_endogenous: true
    operating_range:
    - -1.0
    - 1.0
    red_bounds: null
    yellow_bounds: null
    change_bounds: null
    outlier:
      name: identity
    imputer:
      name: identity
    preprocess:
    - name: normalize
      min: null
      max: null
      from_data: false
    reward_constructor:
    - name: 'null'
    action_constructor: null
    state_constructor:
    - name: multi_trace
      trace_values:
      - 0.0

    filter: null
  - name: tag-7
    agg: avg
    node_identifier: null
    is_meta: false
    is_endogenous: true
    operating_range:
    - -1.0
    - 1.0
    red_bounds: null
    yellow_bounds: null
    change_bounds: null
    outlier:
      name: identity
    imputer:
      name: identity
    preprocess:
    - name: normalize
      min: null
      max: null
      from_data: false
    reward_constructor:
    - name: 'null'
    action_constructor: null
    state_constructor:
    - name: multi_trace
      trace_values:
      - 0.0

    filter: null
  - name: tag-8
    agg: avg
    node_identifier: null
    is_meta: false
    is_endogenous: true
    operating_range:
    - -1.0
    - 1.0
    red_bounds: null
    yellow_bounds: null
    change_bounds: null
    outlier:
      name: identity
    imputer:
      name: identity
    preprocess:
    - name: normalize
      min: null
      max: null
      from_data: false
    reward_constructor:
    - name: 'null'
    action_constructor: null
    state_constructor:
    - name: multi_trace
      trace_values:
      - 0.0

    filter: null
  - name: tag-9
    agg: avg
    node_identifier: null
    is_meta: false
    is_endogenous: true
    operating_range:
    - -1.0
    - 1.0
    red_bounds: null
    yellow_bounds: null
    change_bounds: null
    outlier:
      name: identity
    imputer:
      name: identity
    preprocess:
    - name: normalize
      min: null
      max: null
      from_data: false
    reward_constructor:
    - name: 'null'
    action_constructor: null
    state_constructor:
    - name: multi_trace
      trace_values:
      - 0.0

    filter: null
