defaults:
  -

action_period: 1

env:
  name: tsdb_async_stub_env
  discrete_control: False
  seed: 1
  db: ${pipeline.db}
  bucket_width: "1h"
  env_start_time: "2024-12-15 00:00:00"
  env_end_time: "2024-12-15 23:00:00"
  env_step_time: "1h"
  gym_name: epcor_tsdb_scrubber
  # aggregation: "avg"

agent:
  name: greedy_ac
  n_critic_updates: 1
  n_actor_updates: 1
  n_sampler_updates: 1
  num_samples: 32
  uniform_sampling_percentage: 0.8
  gamma: ${experiment.gamma}
  discrete_control: ${env.discrete_control}
  seed: ${experiment.seed}

  critic:
    buffer:
      seed: ${experiment.seed}

  actor:
    buffer:
      seed: ${experiment.seed}
    actor_optimizer:
      lr: 0.00001

experiment:
  exp_name: epcor_tsdb_scrubber/
  load_path: null
  save_path: output
  max_steps: 100
  online_learning: True
  debug: 0
  seed: 1
  device: cpu
  timeout: 0
  offline_steps: 0
  render: 1
  render_after: 5000
  load_env_obs_space_from_data: False
  param_from_hash: True
  gamma: 0.99
  train_split: 0.9
  plot_split: 0.999
  test_epochs: []
  offline_stat_keys: []
  online_stat_keys: []

pipeline:
  state_constructor:
    defaults: []

  transition_creator:
    name: anytime
    gamma: ${experiment.gamma}

  db:
    drivername: "postgresql+psycopg2"
    username: "postgres"
    password: "password"
    ip: "localhost"
    port: 5432
    db_name: "postgres"
    sensor_table_name: "scrubber4"
    sensor_table_schema: "public"

  tags:
    - name: "AI0879A"
      bounds:
        - 0.05528009682893753
        - 49.91535186767578
      outlier:
        name: "identity"
      imputer:
        name: "identity"
      reward_constructor:
        - name: "null"
      state_constructor: null

    - name: "AI0879B"
      bounds:
        - 0.0
        - 20068.037109375
      outlier:
        name: "identity"
      imputer:
        name: "identity"
      reward_constructor:
        - name: "null"
      state_constructor: null

    - name: "AI0879C"
      bounds:
        - -13323.404296875
        - 100.0
      outlier:
        name: "identity"
      imputer:
        name: "identity"
      reward_constructor:
        - name: "null"
      state_constructor: null

    - name: "AI0897B"
      bounds:
        - 0.3362638056278229
        - 19.93068504333496
      outlier:
        name: "identity"
      imputer:
        name: "identity"
      reward_constructor:
        - name: "null"
      state_constructor: null

    - name: "AIC3730_MODE"
      bounds:
        - 1.0
        - 32.0
      outlier:
        name: "identity"
      imputer:
        name: "identity"
      reward_constructor:
        - name: "null"
      state_constructor: null

    - name: "AIC3730_OUT"
      bounds:
        - 0.0
        - 125.0
      outlier:
        name: "identity"
      imputer:
        name: "identity"
      reward_constructor:
        - name: "null"
      state_constructor: null

    - name: "AIC3730_PV"
      bounds:
        - 1.6386221647262573
        - 11.183662414550781
      outlier:
        name: "identity"
      imputer:
        name: "identity"
      reward_constructor:
        - name: "null"
      state_constructor: null

    - name: "AIC3730_SP"
      bounds:
        - 9.399999618530273
        - 10.0
      outlier:
        name: "identity"
      imputer:
        name: "identity"
      reward_constructor:
        - name: "null"
      state_constructor: null
      tag_type: action

    - name: "AIC3730_SPRL"
      bounds:
        - 9.399999618530273
        - 10.000100135803223
      outlier:
        name: "identity"
      imputer:
        name: "identity"
      reward_constructor:
        - name: "null"
      state_constructor: null

    - name: "AIC3731_MODE"
      bounds:
        - 2.0
        - 32.0
      outlier:
        name: "identity"
      imputer:
        name: "identity"
      reward_constructor:
        - name: "null"
      state_constructor: null

    - name: "AIC3731_OUT"
      bounds:
        - 0.0
        - 125.0
      outlier:
        name: "identity"
      imputer:
        name: "identity"
      reward_constructor:
        - name: "null"
      state_constructor: null

    - name: "AIC3731_PV"
      bounds:
        - -281.9034729003906
        - 801.92333984375
      outlier:
        name: "identity"
      imputer:
        name: "identity"
      reward_constructor:
        - name: "null"
      state_constructor: null

    - name: "AIC3731_SP"
      bounds:
        - 650.0
        - 700.0
      outlier:
        name: "identity"
      imputer:
        name: "identity"
      reward_constructor:
        - name: "null"
      state_constructor: null
      tag_type: action

    - name: "AIC3731_SPRL"
      bounds:
        - 650.0
        - 700.0
      outlier:
        name: "identity"
      imputer:
        name: "identity"
      reward_constructor:
        - name: "null"
      state_constructor: null

    - name: "FI0872"
      bounds:
        - 0.0
        - 2307.52880859375
      outlier:
        name: "identity"
      imputer:
        name: "identity"
      reward_constructor:
        - name: "null"
      state_constructor: null

    - name: "FIC3734_MODE"
      bounds:
        - 8.0
        - 32.0
      outlier:
        name: "identity"
      imputer:
        name: "identity"
      reward_constructor:
        - name: "null"
      state_constructor: null

    - name: "FIC3734_OUT"
      bounds:
        - 0.0
        - 100.0
      outlier:
        name: "identity"
      imputer:
        name: "identity"
      reward_constructor:
        - name: "null"
      state_constructor: null

    - name: "FIC3734_PV"
      bounds:
        - 0.0
        - 60.76387023925781
      outlier:
        name: "identity"
      imputer:
        name: "identity"
      reward_constructor:
        - name: "null"
      state_constructor: null

    - name: "FIC3734_SP"
      bounds:
        - 10.0
        - 50.0
      outlier:
        name: "identity"
      imputer:
        name: "identity"
      reward_constructor:
        - name: "null"
      state_constructor: null
      tag_type: action

    - name: "FIC3734_SPRL"
      bounds:
        - 15.0
        - 50.0
      outlier:
        name: "identity"
      imputer:
        name: "identity"
      reward_constructor:
        - name: "null"
      state_constructor: null

    - name: "FI_0871"
      bounds:
        - 0.0
        - 1530.212890625
      outlier:
        name: "identity"
      imputer:
        name: "identity"
      reward_constructor:
        - name: "null"
      state_constructor: null

    - name: "FV3735_PV"
      bounds:
        - 0.0
        - 1.0
      outlier:
        name: "identity"
      imputer:
        name: "identity"
      reward_constructor:
        - name: "null"
      state_constructor: null

    - name: "LI3734"
      bounds:
        - 580.7721557617188
        - 675.0382690429688
      outlier:
        name: "identity"
      imputer:
        name: "identity"
      reward_constructor:
        - name: "null"
      state_constructor: null

    - name: "M3730A_PV"
      bounds:
        - 0.0
        - 1.0
      outlier:
        name: "identity"
      imputer:
        name: "identity"
      reward_constructor:
        - name: "null"
      state_constructor: null

    - name: "M3730B_PV"
      bounds:
        - 0.0
        - 1.0
      outlier:
        name: "identity"
      imputer:
        name: "identity"
      reward_constructor:
        - name: "null"
      state_constructor: null

    - name: "M3731A_PV"
      bounds:
        - 0.0
        - 1.0
      outlier:
        name: "identity"
      imputer:
        name: "identity"
      reward_constructor:
        - name: "null"
      state_constructor: null

    - name: "M3731B_PV"
      bounds:
        - 0.0
        - 1.0
      outlier:
        name: "identity"
      imputer:
        name: "identity"
      reward_constructor:
        - name: "null"
      state_constructor: null

    - name: "M3739_PV"
      bounds:
        - 0.0
        - 1.0
      outlier:
        name: "identity"
      imputer:
        name: "identity"
      reward_constructor:
        - name: "null"
      state_constructor: null

    - name: "PDIC3738_MODE"
      bounds:
        - 2.0
        - 32.0
      outlier:
        name: "identity"
      imputer:
        name: "identity"
      reward_constructor:
        - name: "null"
      state_constructor: null

    - name: "PDIC3738_OUT"
      bounds:
        - 47.152870178222656
        - 55.0
      outlier:
        name: "identity"
      imputer:
        name: "identity"
      reward_constructor:
        - name: "null"
      state_constructor: null

    - name: "PDIC3738_PV"
      bounds:
        - 0.0490727424621582
        - 3.038361072540283
      outlier:
        name: "identity"
      imputer:
        name: "identity"
      reward_constructor:
        - name: "null"
      state_constructor: null

    - name: "PDIC3738_SP"
      bounds:
        - 2.4000000953674316
        - 2.400099992752075
      outlier:
        name: "identity"
      imputer:
        name: "identity"
      reward_constructor:
        - name: "null"
      state_constructor: null
      tag_type: action

    - name: "PDIC3738_SPRL"
      bounds:
        - 2.399900197982788
        - 2.4001760482788086
      outlier:
        name: "identity"
      imputer:
        name: "identity"
      reward_constructor:
        - name: "null"
      state_constructor: null

    - name: "PI0169"
      bounds:
        - 0.0590519905090332
        - 0.5085716247558594
      outlier:
        name: "identity"
      imputer:
        name: "identity"
      reward_constructor:
        - name: "null"
      state_constructor: null

    - name: "RLCORE_OPCUA_WD"
      bounds:
        - 32.0
        - 32.0
      outlier:
        name: "identity"
      imputer:
        name: "identity"
      reward_constructor:
        - name: "null"
      state_constructor: null

    - name: "TI0880"
      bounds:
        - 0.6180007457733154
        - 19.55890464782715
      outlier:
        name: "identity"
      imputer:
        name: "identity"
      reward_constructor:
        - name: "null"
      state_constructor: null

    - name: "WATCHDOG"
      bounds:
        - 0.0
        - 999.0
      outlier:
        name: "identity"
      imputer:
        name: "identity"
      reward_constructor:
        - name: "null"
      state_constructor: null

    - name: "reward"
      tag_type: meta
      outlier:
        name: "identity"
      imputer:
        name: "identity"

    - name: "terminated"
      tag_type: meta
      outlier:
        name: "identity"
      imputer:
        name: "identity"

    - name: "truncated"
      tag_type: meta
      outlier:
        name: "identity"
      imputer:
        name: "identity"
