agent:
  message_bus:
    enable: False
    host: ''
    port: ''

pipeline:
  db:
    drivername: "postgresql+psycopg2"
    username: "postgres"
    password: "password"
    ip: "localhost"
    port: 5433
    db_name: "pytest"
    table_name: "sensors"
