defaults:
  - base_config
  - agent: greedy_ac
  - env : base_gym_env
  - interaction : anytime
  - data_loader : direct_action
  - state_constructor : identity
  - normalizer/obs_normalizer : identity
  - normalizer/action_normalizer : identity
  - normalizer/reward_normalizer : identity
  # - db: credentials
  - _self_

interaction:
  steps_per_decision: 1

experiment:
  plotting: False
  online_updates : True # Whether to update the agent online in deployment

agent_transition_creator:
  gamma : ${experiment.gamma}
  steps_per_decision : ${interaction.steps_per_decision}
  n_step : ${interaction.n_step}
  only_dp_transitions :  ${interaction.only_dp_transitions}
  transition_kind : anytime

alert_transition_creator: null
calibration_model: null
offline_data: null

use_alerts: False

agent:
  message_bus:
    enable: False
    host: ''
    port: ''

alerts:
eval:
