defaults:
  - base_config
  - agent: greedy_ac
  - env : base_gym_env
  # - db: credentials
  - _self_

experiment:
  plotting: False
  online_updates : True # Whether to update the agent online in deployment

use_alerts: False
action_period: 1

agent:
  message_bus:
    enable: False
    host: ''
    port: ''

pipeline:
  obs_interval_minutes: 5
  db:
    drivername: "postgresql+psycopg2"
    username: "postgres"
    password: "password"
    ip: "localhost"
    port: 5433
    db_name: "pytest"
    sensor_table_name: "sensors"

alerts:
