defaults:
  - base_config
  - agent: greedy_ac
  - env : base_gym_env
  - interaction : anytime
  - data_loader : direct_action
  - state_constructor : identity
  - normalizer/obs_normalizer : identity
  - normalizer/action_normalizer : identity
  - normalizer/reward_normalizer : identity
  - agent_transition_creator: anytime
  # - db: credentials
  - _self_

interaction:
  steps_per_decision: 1

experiment:
  plotting: False
  online_updates : True # Whether to update the agent online in deployment

alert_transition_creator: null
calibration_model: null
offline_data: null

use_alerts: False

agent:
  message_bus:
    enable: False
    host: ''
    port: ''

pipeline:
  obs_interval_minutes: 5
  db:
    drivername: "postgresql+psycopg2"
    username: "postgres"
    password: "password"
    ip: "localhost"
    port: 5433
    db_name: "pytest"
    sensor_table_name: "sensors"

alerts:
eval:
