defaults:
  - env : reseau
  - data_loader : direct_action
  - interaction : normalizer
  - state_constructor: simple_reseau
  - _self_

data_loader:
  offline_data_path : offline_data/reseau/csv
  train_filenames: ["exp.csv", "f_1.csv", "f_b_1.csv", "f_2.csv", "m_b_1.csv", "m_1.csv",
                       "m_b_2.csv", "m_2.csv", "m_3.csv", "rosie.csv", "rosie_2.csv"]
  test_filenames: []
  skip_rows : 3
  header : 0
  df_col_names : ["Blank", "Result", "Table", "Date", "ait101_pv", "ait301_pv", "ait401_pv",
                  "fit101_pv", "fit210_pv", "fit230_pv", "fit250_pv", "fit401_pv", "p250_fp",
                  "pt100_pv", "pt101_pv", "pt161_pv", "pt171_pv", "pt302_pv"]
  action_col_names: ["p250_fp"]

  # NOTE: the endo will come first in the SC
  obs_col_names: ["ait301_pv", "fit250_pv"]


output_path : offline_data/reseau
experiment:
  seed : 0
  timeout: 0
  gamma : 0.9


interaction:
  obs_length: 60
  steps_per_decision: 30
  action_normalizer:
    action_high: 300
    action_low: 0
  reward_normalizer:
    reward_high: 4
    reward_low: -20
    reward_bias: 4

