defaults:
  - env: env/saturation

interaction:
  name: sim_interaction
  obs_period: 00:00:01
  action_period: 00:00:02

experiment :
  exp_name : "saturation"
  max_steps : 5000

metrics:
  enabled: True


agent:
  name: greedy_ac

  critic:
    polyak: 0.995
    critic_optimizer:
      name: 'lso'
      lr : 0.01
      weight_decay : 0.0
    critic_network:
      ensemble: 1
    buffer:
      name : 'ensemble_uniform'
      ensemble: 2

pipeline:
  state_constructor:
    default:
      - name: multi_trace
        trace_values: [0.999, 0.99, 0.95, 0.9, 0.8, 0.7, 0.6, 0.5]

  transition_creator:
   name: anytime
   gamma: 0.9

  tags:
  # meta tags
  - name: reward
    preprocess:
    - name: identity
    reward_constructor:
    - name: identity
    state_constructor:
    - name: 'null'

  - name: terminated
    is_meta: True

  - name: truncated
    is_meta: True

  # observations
  - name: tag-0
    operating_range: [0, 0.5]

  # actions
  - name: action-0
    operating_range: [0, 1]
    action_constructor:
      - name: identity
