defaults:
  - env: env/saturation

interaction:
  name: sim_interaction
  obs_period: 00:00:01
  action_period: 00:00:02

experiment :
  exp_name : "saturation"
  max_steps : 5000

metrics:
  enabled: True


agent:
  name: greedy_ac
  rho : 0.1
  num_samples: 100
  seed: ${experiment.seed}
  gamma: ${experiment.gamma}
  discrete_control: ${env.discrete_control}

  critic:
    polyak: 0.995
    critic_optimizer:
      name: 'lso'
      lr : 0.01
      weight_decay : 0.0
    critic_network:
      ensemble: 1
    buffer:
      name : 'ensemble_uniform'
      ensemble: 2

  actor:
    actor_optimizer:
      lr : 0.0005


pipeline:
  state_constructor:
    default:
      - name: multi_trace
        trace_values: [0.999, 0.99, 0.95, 0.9, 0.8, 0.7, 0.6, 0.5]

  transition_creator:
   name: anytime
   gamma: 0.9

  tags:
  # meta tags
  - name: reward
    preprocess:
    - name: identity
    outlier:
      name: identity
    reward_constructor:
    - name: identity
    state_constructor:
    - name: 'null'
    preprocess:
    - name: identity

  - name: terminated
    preprocess:
    - name: identity
    is_meta: True
    outlier:
      name: identity

  - name: truncated
    preprocess:
    - name: identity
    is_meta: True
    outlier:
      name: identity

  # observations
  - name: tag-0
    preprocess:
    - name: identity
    outlier:
      name: identity

  # actions
  - name: action-0
    operating_range: [0, 1]
    preprocess:
    - name: identity
    outlier:
      name: identity
    action_constructor:
      - name: identity
