defaults:
  - gym
  - env: env/saturation

interaction:
  name: sim_interaction
  obs_period: 00:00:01
  action_period: 00:00:01

experiment :
  exp_name : "saturation"
  max_steps : 5000
  offline_steps : 0
  timeout: 0

metrics:
  name : db
  drivername: "postgresql+psycopg2"
  username: "postgres"
  password: "password"
  ip: "localhost"
  port: 5432
  db_name: "postgres"
  table_schema: "public"
  table_name: "metrics"
  enabled: True


agent:
  name: greedy_ac
  rho : 0.1
  num_samples: 100
  seed: ${experiment.seed}
  gamma: ${experiment.gamma}
  discrete_control: ${env.discrete_control}

  critic:
    polyak: 0.995
    critic_optimizer:
      lr : 0.0003
      weight_decay : 0.0
    buffer:
      name: uniform
      seed: ${experiment.seed}

  actor:
    actor_optimizer:
      lr : 0.0005
    buffer:
      name: uniform
      seed: ${experiment.seed}


pipeline:
  state_constructor:
    defaults: []

  transition_creator:
   name: anytime
   gamma: 0.9

  tags:
  # meta tags
  - name: reward
    preprocess:
    - name: identity
    outlier:
      name: identity
    reward_constructor:
    - name: identity
    state_constructor:
    - name: 'null'
    preprocess:
    - name: identity

  - name: terminated
    preprocess:
    - name: identity
    is_meta: True
    outlier:
      name: identity

  - name: truncated
    preprocess:
    - name: identity
    is_meta: True
    outlier:
      name: identity
    state_constructor:
    - name: 'null'

  # observations
  - name: tag-0
    is_meta: False
    preprocess:
    - name: identity
    outlier:
      name: identity
    state_constructor:
    - name: multi_trace
      trace_values: [0.999, 0.99, 0.95, 0.9, 0.8, 0.7, 0.6, 0.5]

  # actions
  - name: action-0
    is_meta: False
    operating_range: [0, 1]
    preprocess:
    - name: identity
    outlier:
      name: identity
    state_constructor:
    - name: multi_trace
      trace_values: [0.999, 0.99, 0.95, 0.9, 0.8, 0.7, 0.6, 0.5]
    action_constructor:
      - name: identity
  