# This is a minimal config that still passes the test_main_configs test
experiment:
  exp_name: My_Experiment

interaction:
  name: dep_interaction
  action_period: 00:00:01
  obs_period: 00:00:01
  update_period: 00:00:05
  state_age_tol: 00:00:01

env:
  name: dep_async_env

agent:
  name: greedy_ac
