seed: 1

interaction:
  name: sim_interaction
  obs_period: 00:00:01
  action_period: 00:00:01

metrics:
  enabled: False

env:
  name: sim_async_env
  gym:
    gym_name: MountainCarContinuous-v0
    init_type: gym.make

agent:
  name: greedy_ac
  gamma: 0.99

pipeline:
  tags:
  - name: reward
    type: meta

  - name: terminated
    type: meta

  - name: truncated
    type: meta

  - name: action-0
    type: ai_setpoint
    operating_range: [-1, 1]

  - name: tag-0
    operating_range: [-1.2, 0.6]

  - name: tag-1
    operating_range: [-0.07, 0.07]
