experiment:
  exp_name: MountainCarContinuous
  seed: 1
  gamma: 0.99

interaction:
  name: sim_interaction
  obs_period: 00:00:01
  action_period: 00:00:01

metrics:
  enabled: False

env:
  name: sim_async_env
  gym_name: MountainCarContinuous-v0
  discrete_control: False
  seed: 1

agent:
  name: greedy_ac
  n_critic_updates: 1
  n_actor_updates: 1
  num_samples: 32
  uniform_sampling_percentage: 0.8
  discrete_control: ${env.discrete_control}
  seed: ${experiment.seed}

  critic:
    buffer:
      name: uniform
      seed: ${experiment.seed}

  actor:
    buffer:
      name: uniform
      seed: ${experiment.seed}
    actor_optimizer:
      lr: 0.00001

pipeline:
  state_constructor:
    defaults: []

  transition_creator:
    name: anytime

  tags:
  - name: reward
    preprocess:
    - name: identity
    outlier:
      name: identity
    imputer:
      name: identity
    reward_constructor:
    - name: identity
    is_meta: true

  - name: terminated
    preprocess:
    - name: identity
    outlier:
      name: identity
    imputer:
      name: identity
    is_meta: true

  - name: truncated
    preprocess:
    - name: identity
    outlier:
      name: identity
    imputer:
      name: identity
    is_meta: true

  - name: action-0
    operating_range: [-1, 1]
    outlier:
      name: identity
    imputer:
      name: identity
    state_constructor:
      - name: 'null'
    action_constructor:
      - name: normalize
        min: -1
        max: 1
        from_data: False

  - name: tag-0
    operating_range: [-1.2, 0.6]
    outlier:
      name: identity
    imputer:
      name: identity

  - name: tag-1
    operating_range: [-0.07, 0.07]
    outlier:
      name: identity
    imputer:
      name: identity
