experiment:
  exp_name: MountainCarContinuous
  seed: 1
  gamma: 0.99

interaction:
  name: sim_interaction
  obs_period: 00:00:01
  action_period: 00:00:01

metrics:
  enabled: False

env:
  name: sim_async_env
  gym_name: MountainCarContinuous-v0
  discrete_control: False
  seed: 1

agent:
  name: greedy_ac

pipeline:
  transition_creator:
    name: anytime

  tags:
  - name: reward
    preprocess:
    - name: identity
    reward_constructor:
    - name: identity
    state_constructor:
    - name: 'null'

  - name: terminated
    preprocess:
    - name: identity
    is_meta: true

  - name: truncated
    preprocess:
    - name: identity
    is_meta: true

  - name: action-0
    operating_range: [-1, 1]
    state_constructor:
      - name: 'null'
    action_constructor:
      - name: identity

  - name: tag-0
    operating_range: [-1.2, 0.6]

  - name: tag-1
    operating_range: [-0.07, 0.07]
