defaults:
  -

experiment:
  seed: 1
  gamma: 0.99

interaction:
  name: sim_interaction

env:
  name: sim_async_env
  gym_name: MountainCarContinuous-v0
  discrete_control: False
  seed: 1
  db: ${pipeline.db}
  action_period: 00:00:01
  obs_period: 00:00:01

agent:
  name: greedy_ac
  n_critic_updates: 1
  n_actor_updates: 1
  n_sampler_updates: 1
  num_samples: 32
  uniform_sampling_percentage: 0.8
  discrete_control: ${env.discrete_control}
  seed: ${experiment.seed}

  critic:
    buffer:
      seed: ${experiment.seed}

  actor:
    buffer:
      seed: ${experiment.seed}
    actor_optimizer:
      lr: 0.00001


pipeline:
  db:
    drivername: "postgresql+psycopg2"
    username: "postgres"
    password: "password"
    ip: "localhost"
    port: 5432
    db_name: "public"
    sensor_table_name: "sensors"

  state_constructor:
    defaults: []

  transition_creator:
    name: anytime

  tags:
  - name: reward
    bounds:
    - null
    - null
    outlier:
      name: identity
    imputer:
      name: identity
    reward_constructor:
    - name: 'null'
    state_constructor: null
    is_action: false
    is_meta: true
  - name: terminated
    bounds:
    - null
    - null
    outlier:
      name: identity
    imputer:
      name: identity
    reward_constructor:
    - name: 'null'
    state_constructor: null
    is_action: false
    is_meta: true
  - name: truncated
    bounds:
    - null
    - null
    outlier:
      name: identity
    imputer:
      name: identity
    reward_constructor:
    - name: 'null'
    state_constructor: null
    is_action: false
    is_meta: true
  - name: action_0
    bounds:
    - -1.0
    - 1.0
    outlier:
      name: identity
    imputer:
      name: identity
    reward_constructor:
    - name: 'null'
    state_constructor: null
    is_action: true
    is_meta: false
  - name: observation_0
    bounds:
    - -1.2
    - 0.6
    outlier:
      name: identity
    imputer:
      name: identity
    reward_constructor:
    - name: 'null'
    state_constructor: null
    is_action: false
    is_meta: false
  - name: observation_1
    bounds:
    - -0.07
    - 0.07
    outlier:
      name: identity
    imputer:
      name: identity
    reward_constructor:
    - name: 'null'
    state_constructor: null
    is_action: false
    is_meta: false
