defaults:
  - config
  - override agent: greedy_ac
  - override env: saturation
  - override data_loader: direct_action
  - override interaction: anytime
  - override calibration_model : one_step
  - override state_constructor: multi_trace
  - _self_

offline_data:
  load_from : transition
  output_path : offline_data/saturation

experiment :
  exp_name : "saturation"
  max_steps : 5000
  offline_steps : 0
  set_env_obs_space : True
  timeout: 0


env:
  opc : null
  db : null

interaction :
  action_normalizer:
    use_cfg_values : False

agent:
  tau : 0
  rho : 0.05
  num_samples: 100
  uniform_proposal : True
  critic:
    polyak': 0.995
    critic_optimizer:
      lr : 0.0003
      weight_decay : 0.0
  actor:
    actor_optimizer:
      lr : 0.001

alerts:
  action_value:
    gamma : 0.8
    ret_perc : 0.1
    trace_decay : 0.995
    trace_thresh : 0.1
  gvf:
    endo_obs_col_names: ["saturation"]
    gamma : 0.8
    ret_perc : 0.1
    trace_decay : 0.995
    trace_thresh : 0.1
