defaults:
  - env: env/saturation

interaction:
  name: sim_interaction
  obs_period: 00:00:01
  action_period: 00:00:01

experiment :
  exp_name : "saturation"
  max_steps : 10000

metrics:
  enabled: False

agent:
  name: greedy_ac

  critic:
    critic_network:
      ensemble: 10

  policy:
    optimizer:
      lr : 0.0005

pipeline:
  state_constructor:
    defaults:
      - name: multi_trace
        trace_values: [0.0, 0.9, 0.95, 0.99]

  tags:
  # meta tags
  - name: reward
    type: meta

  - name: terminated
    type: meta

  - name: truncated
    type: meta

  # observations
  - name: tag-0
    operating_range: [0, 1]

  # actions
  - name: action-0
    type: ai_setpoint
    operating_range: [0, 0.5]
