defaults:
  - config
  - alerts@alerts.gvf_trace : gvf_trace
  - override agent: greedy_ac
  - override env: delayed_saturation
  - override data_loader: direct_action
  - override interaction: anytime
  - override calibration_model : one_step
  - override state_constructor: anytime_multi_trace
  - override hydra/launcher: joblib
  - _self_

use_alerts : True

offline_data:
  load_from : transition
  output_path : offline_data/saturation

state_constructor:
  use_indicator : True
  representation : thermometer

experiment :
  exp_name : "delayed_saturation_debug"
  max_steps : 10000
  offline_steps : 0
  set_env_obs_space : False
  timeout: 0

env:
  opc : null
  db : null

interaction :
  obs_length: 1
  only_dp_transitions : False
  steps_per_decision: 7
  n_step : 0
  action_normalizer:
    use_cfg_values : False

agent:
  tau : 0
  rho : 0.05
  num_samples: 100
  uniform_proposal : True
  critic:
    polyak': 0.995
    critic_optimizer:
      lr : 0.0003
      weight_decay : 0.0
  actor:
    actor_optimizer:
      lr : 0.001
  buffer:
      batch_size : 64

data_loader:
  offline_data_path: offline_data/saturation/csv
  train_filenames: ["data.csv"]
  test_filenames: ["data.csv"]
  skip_rows: 0
  header: 0
  df_col_names: ["index", "saturation", "action", "time"]
  date_col_name : "time"
  action_col_names: ["action"]
  obs_col_names: ["saturation"]
