defaults:
  - env: env/saturation

interaction:
  name: sim_interaction
  obs_period: 00:00:01
  action_period: 00:00:01

experiment :
  exp_name : "saturation"
  max_steps : 10000

metrics:
  enabled: False

agent:
  name: greedy_ac
  rho : 0.05
  num_samples: 100
  seed: ${experiment.seed}
  gamma: ${experiment.gamma}
  discrete_control: ${env.discrete_control}

  critic:
    polyak: 0.995
    critic_optimizer:
      lr : 0.0003
      weight_decay : 0.0
    critic_network:
      ensemble: 10
    buffer:
      name: ensemble_uniform
      seed: ${experiment.seed}
      ensemble: 10

  actor:
    actor_optimizer:
      lr : 0.0005
    buffer:
      name: uniform
      seed: ${experiment.seed}

pipeline:
  state_constructor:
    defaults:
      - name: multi_trace
        trace_values: [0.0, 0.9, 0.95, 0.99]

  transition_creator:
    name: anytime
    gamma: ${experiment.gamma}

  tags:
  # meta tags
  - name: reward
    preprocess:
    - name: identity
    outlier:
      name: identity
    reward_constructor:
    - name: identity
    state_constructor:
    - name: 'null'
    preprocess:
    - name: identity

  - name: terminated
    preprocess:
    - name: identity
    is_meta: True
    outlier:
      name: identity

  - name: truncated
    preprocess:
    - name: identity
    is_meta: True
    outlier:
      name: identity
    state_constructor:
    - name: 'null'

  # observations
  - name: tag-0
    preprocess:
    - name: identity
    is_meta: False
    outlier:
      name: identity

  # actions
  - name: action-0
    is_meta: False
    operating_range: [-2, 2]
    outlier:
      name: identity
    state_constructor:
      - name: 'null'
    preprocess:
      - name: normalize
        from_data: False
    action_constructor:
      - name: identity
