defaults:
  - env: env/three_tanks

interaction:
  name: sim_interaction
  obs_period: 00:00:01
  action_period: 00:00:01

experiment:
  exp_name: "three_tanks"
  max_steps: 2000
  gamma: 0.99

metrics:
  enabled: True

agent:
  name: greedy_ac

  critic:
    critic_network:
      ensemble: 1
    critic_optimizer:
      lr: 0.00025

  actor:
    actor_optimizer:
      lr: 0.0005

pipeline:
  state_constructor:
    defaults:
      - name: identity

  transition_creator:
    name: anytime
    gamma: 0.99

  tags:
  # meta tags
  - name: reward
    preprocess:
    - name: identity
    reward_constructor:
    - name: identity
    state_constructor:
    - name: 'null'
    operating_range: [-1, 0]

  - name: terminated
    is_meta: True

  - name: truncated
    is_meta: True

  # observations
  - name: tag-0
    operating_range: [0, 43.1]  # Based on height clipping in the environment
  - name: tag-1
    operating_range: [0, 43.1]
  - name: tag-2
    operating_range: [0, 43.1]
  - name: tag-3
    operating_range: [0, 43.1]
  - name: tag-4
    operating_range: [0, 43.1]

  # actions
  - name: action-0
    operating_range: [0, 100]  
    state_constructor:
      - name: 'null'
    action_constructor:
      - name: identity
  - name: action-1
    operating_range: [0, 100] 
    state_constructor:
      - name: 'null'
    action_constructor:
      - name: identity
