interaction:
  name: dep_interaction
  action_period: PT5M
  obs_period: PT5M

metrics:
  table_name: metrics
  enabled: true

infra:
  db:
    username: postgres
    password: password
    ip: localhost
    port: 5432
    db_name: postgres


experiment:
  exp_name: CoreRL_Experiment
