feature_flags:
  zone_violations: true

env:
  name: sim_async_env
  gym:
    gym_name: WindyRoom-v0

interaction:
  name: sim_interaction
  obs_period: 00:00:01
  action_period: 00:00:01

experiment:
  exp_name: "windy_room"
  max_steps: 5000
  gamma: 0.95


metrics:
  enabled: True

pipeline:
  tags:
  # meta tags
  - name: reward
    type: meta

  - name: terminated
    type: meta

  - name: truncated
    type: meta

  - name: action-0
    type: ai_setpoint
    operating_range: [-1, 1]

  - name: action-1
    type: ai_setpoint
    operating_range: [-1, 1]

  - name: tag-0 # x position`
    operating_range: [0, 1]
    red_bounds: [0.05, 0.95]
    yellow_bounds: [0.3, 0.7]

  - name: tag-1 # y position
    operating_range: [0, 1]
    red_bounds: [0.05, 0.95]
    yellow_bounds: [0.3, 0.7]

  - name: tag-2 # wind angle in radians
    operating_range: [0., 6.29]
