defaults:
  - base_agent
  - critic: critic_linesearch
  - actor : network_linesearch
  - buffer: uniform
  - exploration: random_linear_linesearch
  - _self_

name : greedy_ac_linesearch_explore
average_entropy : True
tau : 0.0
rho : 0.2
prop_rho_mult : 2.0
num_samples : 100
temp : 0.0
device : ${experiment.device}

exploration_weight: 0.1