defaults:
  - base_agent
  - critic: critic_linesearch
  - actor : network_linesearch
  - buffer: uniform
  - _self_

name : greedy_ac_linesearch
average_entropy : True
tau : 0.0
rho : 0.2
prop_rho_mult : 2.0
num_samples : 100
share_batch : True
temp : 0.0
uniform_proposal : False
n_sampler_updates: 1
n_critic_updates : 1
n_actor_updates : 1



