defaults:
  - base_agent
  - critic: critic_linesearch
  - actor : network_linesearch
  - buffer: uniform
  - _self_

name : greedy_ac_linesearch
average_entropy : True
tau : 0.0
rho : 0.2
prop_rho_mult : 2.0
n : 500
temp : 1.0
device : ${experiment.device}

