defaults:
  - base_ac
  - _self_

name : greedy_ac
average_entropy : True
tau : 0.0
rho : 0.1
prop_rho_mult : 2.0
num_samples : 500
share_batch : True
uniform_proposal : True
n_sampler_updates: 1
# Whether all critics in the ensemble should use their own targets or an
# aggregate target based on the ensemble reduct function
ensemble_targets: True


