defaults:
  - base_agent
  - critic: critic
  - actor : network
  - buffer: uniform
  - _self_

name : gac
average_entropy : True
tau : 0.0
rho : 0.2
prop_rho_mult : 2.0
n : 500
temp : 1.0
device : ${experiment.device}

