defaults:
  - base_agent
  - critic: critic
  - actor : network
  - buffer: uniform
  - _self_

name : greedy_ac
average_entropy : True
tau : 0.0
rho : 0.2
prop_rho_mult : 2.0
num_samples : 100
uniform_proposal : False

