defaults:
 - pipeline: tags
 - env.db: db


report:
  cross_corr_tags : null
  cross_corr_max_lag : 300

interaction:
  name: dep_interaction
  obs_period: 00:05:00
  action_period: 01:00:00
  heartbeat:
    heartbeat_node_id: s=heartbeat


agent:
  name: greedy_ac

env:
  name: dep_async_env
  obs_period: 00:05:00
  update_period: 00:05:00
  action_period: 01:00:00
  seed: ${experiment.seed}
  opc_conn_url: "opc.tcp://ignition-services:62541"
  opc_ns: 1
  discrete_control: False
  action_tolerance: 01:00:00

experiment:
  exp_name: cenovus
  save_path: output
  max_steps: 10000
  seed: 1
  offline_steps: 10
  pipeline_batch_duration: 7 days
  gamma: 0.99

pipeline:
  transition_creator:
    name: anytime
    gamma: ${experiment.gamma}
