tags:
  - name: BSW_PDO_Perc
    is_action: true
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 64.3878913092831
        max: 71.54707736724436


  - name: BW_Flow
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 60.30093
    reward_constructor:
      - name: identity


  - name: Bed Profile - Central Mix Zone
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 30.0


  - name: Bed Profile - Reaction Zone
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 2.0
        max: 40.0


  - name: Bed Profile - Tap 1
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 8.0
        max: 99.0


  - name: Bed Profile - Tap 2
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 50.0


  - name: Bed Profile - Tap 3
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 40.0


  - name: CDE_PW_xOver_DOTk_Flow
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 509.9978631591797


  - name: Coagulant Concentration
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: -0.35402339696884155
        max: 46.41282653808594


  - name: Coagulant Flow Rate
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: -7.014660358428394
        max: 1078.3374023436636


  - name: FWKO_Inlet_Flow
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 106.260628
        max: 1284.91272


  - name: FWKO_RBW_FlowA
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 6e-323
        max: 20.57544783214297


  - name: FWKO_RBW_FlowB
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 42.39501


  - name: FWKO_RBW_Total_Flow
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 42.39501


  - name: Filter Aid Concentration
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 0.0


  - name: Filter Aid Flow Rate
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 0.0


  - name: Heater_Steam_Flow
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 11137.59225204419


  - name: IGF_Oil_Flow
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 76.736


  - name: IGF_POLY_PPM
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 4.0
        max: 37.0


  - name: IGF_Poly_Flow
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 4.0
        max: 37.0


  - name: Inlet Oil and Grease Concentration
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 195.0


  - name: Inlet Oil and Grease Flow Rate
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 176.6137361368976


  - name: Inlet Produced Water Flow Rate
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 1012.5806274414062


  - name: Inlet_Degasser_DMO_FlowA
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 0.0


  - name: Inlet_Degasser_DMO_FlowB
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 0.0


  - name: Inlet_Degasser_DMO_Total_Flow
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 0.0


  - name: Lime Slurry Flow Rate
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 43.449092864990234


  - name: Lime Slurry Strength
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 1.5
        max: 18.0


  - name: MagOx Slurry Flow Rate
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 49.745574951171875


  - name: MagOx Slurry Strength
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.3
        max: 6.0


  - name: ORF_Bypass_Flow
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: -9.15769457844759
        max: 790.0190021377844


  - name: ORF_Feed_Flow
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 391.85437
        max: 1219.80164


  - name: Outlet Hardness
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 12.0
        max: 205.0


  - name: Outlet Oil and Grease Concentration
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 9.4


  - name: Outlet Oil and Grease Flow Rate
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 8.229918755709846


  - name: Outlet Silica
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 14.42
        max: 221.41


  - name: Outlet Turbidity
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 36.0


  - name: Outlet pH
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 8.5
        max: 96.0


  - name: PW_BW_Flow
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 1012.58063


  - name: PW_Treated_Recyc
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 655.937866


  - name: PolyA_PPM
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 3.063157


  - name: PolyB_PPM
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 8.0


  - name: Polymer Concentration
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 8.0


  - name: Polymer Flow Rate
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 164.28433227537747


  - name: Rake Lift
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 5.984619617462158


  - name: Rake Torque
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.021901726722717285
        max: 30.11444854736328


  - name: Reaction Zone pH
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 9.1
        max: 10.7


  - name: Silica_In
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 2.0
        max: 121.0


  - name: Skim_PW_Flow
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 17.6106873
        max: 1264.51257


  - name: Skim_Poly_Flow
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 138.0
        max: 278.0


  - name: Skim_Poly_PPM
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 138.0
        max: 278.0


  - name: Sludge Recycle Flow Rate
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 164.40896606445312


  - name: Sludge_Centrifuge
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 12.770114421844482


  - name: Sludge_Recycle_Ratio
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 48.89717235342511


  - name: Slug_Catcher_Liquids_Flow
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 1e-323
        max: 150.4712279743713


  - name: Tap_4
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 40.0


  - name: Tap_5
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 35.0


  - name: Tap_6
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 1.0


  - name: Tap_7
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 0.0


  - name: Temp_In
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 81.86226081848145
        max: 95.16987991333008


  - name: Temperature
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 78.88799285888672
        max: 91.90753173828125


  - name: Water Recycle Flow Rate
    is_action: false
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 655.9378662109375
