tags:
  - name: BSW_PDO_Perc
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 64.3878913092831
        max: 71.54707736724436
    action_constructor:
      - name: 'identity'


  - name: BW_Flow
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 60.30093
    action_constructor:
      - name: 'null'
    reward_constructor:
      - name: identity


  - name: Bed Profile - Central Mix Zone
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 30.0
    action_constructor:
      - name: 'null'


  - name: Bed Profile - Reaction Zone
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 2.0
        max: 40.0
    action_constructor:
      - name: 'null'


  - name: Bed Profile - Tap 1
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 8.0
        max: 99.0
    action_constructor:
      - name: 'null'


  - name: Bed Profile - Tap 2
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 50.0
    action_constructor:
      - name: 'null'


  - name: Bed Profile - Tap 3
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 40.0
    action_constructor:
      - name: 'null'


  - name: CDE_PW_xOver_DOTk_Flow
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 509.9978631591797
    action_constructor:
      - name: 'null'


  - name: Coagulant Concentration
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: -0.35402339696884155
        max: 46.41282653808594
    action_constructor:
      - name: 'null'


  - name: Coagulant Flow Rate
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: -7.014660358428394
        max: 1078.3374023436636
    action_constructor:
      - name: 'null'


  - name: FWKO_Inlet_Flow
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 106.260628
        max: 1284.91272
    action_constructor:
      - name: 'null'


  - name: FWKO_RBW_FlowA
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 6e-323
        max: 20.57544783214297
    action_constructor:
      - name: 'null'


  - name: FWKO_RBW_FlowB
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 42.39501
    action_constructor:
      - name: 'null'


  - name: FWKO_RBW_Total_Flow
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 42.39501
    action_constructor:
      - name: 'null'


  - name: Filter Aid Concentration
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 0.0
    action_constructor:
      - name: 'null'


  - name: Filter Aid Flow Rate
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 0.0
    action_constructor:
      - name: 'null'


  - name: Heater_Steam_Flow
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 11137.59225204419
    action_constructor:
      - name: 'null'


  - name: IGF_Oil_Flow
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 76.736
    action_constructor:
      - name: 'null'


  - name: IGF_POLY_PPM
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 4.0
        max: 37.0
    action_constructor:
      - name: 'null'


  - name: IGF_Poly_Flow
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 4.0
        max: 37.0
    action_constructor:
      - name: 'null'


  - name: Inlet Oil and Grease Concentration
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 195.0
    action_constructor:
      - name: 'null'


  - name: Inlet Oil and Grease Flow Rate
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 176.6137361368976
    action_constructor:
      - name: 'null'


  - name: Inlet Produced Water Flow Rate
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 1012.5806274414062
    action_constructor:
      - name: 'null'


  - name: Inlet_Degasser_DMO_FlowA
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 0.0
    action_constructor:
      - name: 'null'


  - name: Inlet_Degasser_DMO_FlowB
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 0.0
    action_constructor:
      - name: 'null'


  - name: Inlet_Degasser_DMO_Total_Flow
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 0.0
    action_constructor:
      - name: 'null'


  - name: Lime Slurry Flow Rate
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 43.449092864990234
    action_constructor:
      - name: 'null'


  - name: Lime Slurry Strength
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 1.5
        max: 18.0
    action_constructor:
      - name: 'null'


  - name: MagOx Slurry Flow Rate
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 49.745574951171875
    action_constructor:
      - name: 'null'


  - name: MagOx Slurry Strength
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.3
        max: 6.0
    action_constructor:
      - name: 'null'


  - name: ORF_Bypass_Flow
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: -9.15769457844759
        max: 790.0190021377844
    action_constructor:
      - name: 'null'


  - name: ORF_Feed_Flow
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 391.85437
        max: 1219.80164
    action_constructor:
      - name: 'null'


  - name: Outlet Hardness
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 12.0
        max: 205.0
    action_constructor:
      - name: 'null'


  - name: Outlet Oil and Grease Concentration
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 9.4
    action_constructor:
      - name: 'null'


  - name: Outlet Oil and Grease Flow Rate
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 8.229918755709846
    action_constructor:
      - name: 'null'


  - name: Outlet Silica
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 14.42
        max: 221.41
    action_constructor:
      - name: 'null'


  - name: Outlet Turbidity
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 36.0
    action_constructor:
      - name: 'null'


  - name: Outlet pH
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 8.5
        max: 96.0
    action_constructor:
      - name: 'null'


  - name: PW_BW_Flow
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 1012.58063
    action_constructor:
      - name: 'null'


  - name: PW_Treated_Recyc
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 655.937866
    action_constructor:
      - name: 'null'


  - name: PolyA_PPM
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 3.063157
    action_constructor:
      - name: 'null'


  - name: PolyB_PPM
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 8.0
    action_constructor:
      - name: 'null'


  - name: Polymer Concentration
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 8.0
    action_constructor:
      - name: 'null'


  - name: Polymer Flow Rate
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 164.28433227537747
    action_constructor:
      - name: 'null'


  - name: Rake Lift
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 5.984619617462158
    action_constructor:
      - name: 'null'


  - name: Rake Torque
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.021901726722717285
        max: 30.11444854736328
    action_constructor:
      - name: 'null'


  - name: Reaction Zone pH
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 9.1
        max: 10.7
    action_constructor:
      - name: 'null'


  - name: Silica_In
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 2.0
        max: 121.0
    action_constructor:
      - name: 'null'


  - name: Skim_PW_Flow
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 17.6106873
        max: 1264.51257
    action_constructor:
      - name: 'null'


  - name: Skim_Poly_Flow
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 138.0
        max: 278.0
    action_constructor:
      - name: 'null'


  - name: Skim_Poly_PPM
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 138.0
        max: 278.0
    action_constructor:
      - name: 'null'


  - name: Sludge Recycle Flow Rate
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 164.40896606445312
    action_constructor:
      - name: 'null'


  - name: Sludge_Centrifuge
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 12.770114421844482
    action_constructor:
      - name: 'null'


  - name: Sludge_Recycle_Ratio
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 48.89717235342511
    action_constructor:
      - name: 'null'


  - name: Slug_Catcher_Liquids_Flow
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 1e-323
        max: 150.4712279743713
    action_constructor:
      - name: 'null'


  - name: Tap_4
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 40.0
    action_constructor:
      - name: 'null'


  - name: Tap_5
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 35.0
    action_constructor:
      - name: 'null'


  - name: Tap_6
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 1.0
    action_constructor:
      - name: 'null'


  - name: Tap_7
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 0.0
    action_constructor:
      - name: 'null'


  - name: Temp_In
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 81.86226081848145
        max: 95.16987991333008
    action_constructor:
      - name: 'null'


  - name: Temperature
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 78.88799285888672
        max: 91.90753173828125
    action_constructor:
      - name: 'null'


  - name: Water Recycle Flow Rate
    imputer:
      name: copy
      imputation_horizon: 60
    state_constructor:
      - name: normalize
        min: 0.0
        max: 655.9378662109375
    action_constructor:
      - name: 'null'
