name : gvf
endo_obs_names: ${env.endo_obs_names}
endo_inds : ${env.endo_inds}
gamma : 0.8
ret_perc : 0.1 # Percentage of observed return not used to compute the observed partial return
trace_decay : 0.995
trace_thresh : 0.1
train_itr : 1000
critic : ${agent.critic}
buffer : ${agent.buffer}