name: example
max_steps: 100

agent:
  name: base

  num_samples: 128
  actor_percentile: 0.1
  proposal_percentile: 0.2
  uniform_weight: 1.0
  batch_size: 256
  ensemble: 1
  ensemble_prob: 1.0

  actor_lr: 0.001
  proposal_lr: 0.001
  critic_lr: 0.1
  polyak: 0.995
