name: example
max_steps: 100

agent:
  name: base

  num_samples: 128
  actor_percentile: 0.1
  proposal_percentile: 0.2
  uniform_weight: 1.0
  batch_size: 256

  actor_lr: 0.001
  proposal_lr: 0.001

  critic:
    stepsize: 0.1
    ensemble: 1
    ensemble_prob: 1.0
    batch_size: 256
    polyak: 0.995

env:
  name: Saturation-v0
