  batch_size: 512
  memory: 100000
  name: sql_buffer
  device : ${experiment.device}
  seed : ${experiment.seed}
  db_name: test_db
  only_new_transitions: True
  con_cfg:  
    username: "eng"
    password: "rlcore"
    ip: "10.123.10.55"
    port: 3306