name: ibe
gamma: ${agent.gamma}
n_updates: 10

optimizer:
  name: adam
  lr: 0.001
  weight_decay: 0.0

network:
  layer_norm : 0
  arch : [256, 256]
  init_args : ReLU
  head_activation : ReLU
  activation : ReLU
  layer_init : Xavier
  bias : True
  name: fc