name: ibe
gamma: ${agent.gamma}
n_updates: 1

optimizer:
  name: adam
  lr: 0.0001
  weight_decay: 0.0


network:
  name: ensemble_fc
  ensemble : ${agent.critic.critic_network.ensemble}
  base:
    name: fc

    # Neural network composed of two hidden layers of 64 units with the ReLU
    # activation after the first and second hidden layers after the second hidden
    # layer
    hidden : [256, 256]

    activation : [
      {"name": "relu"}, {"name": "relu"},
    ]

    bias: True
    layer_init : Xavier

offline_eval : True
online_eval : True
