name: CoreRL Style and Tests
permissions: write-all # Needed to comment coverage% on PR

on:
  pull_request:
    paths:
      - "corerl/**"
      - "libs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # -----------
  # -- Style --
  # -----------
  corerl-style-n-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: corerl

    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          subrepo: corerl

      - name: set up path
        run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

      # linting
      - uses: astral-sh/ruff-action@v1
        with:
            src: corerl

      - uses: dciborow/action-pylint@0.1.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
          workdir: corerl
          glob_pattern: "corerl/ tests/"

      # type checking
      - uses: jakebailey/pyright-action@v2
        with:
          pylance-version: latest-release
          working-directory: corerl

      # -----------
      # -- Tests --
      # -----------
      - name: Create artifact directory
        run: mkdir -p artifact

      - name: Run Pytest
        run: |
          pytest -n auto --dist loadscope --cov=. --cov-append tests/small
          pytest -n auto --dist loadscope --cov=. --cov-append tests/medium
          pytest -n auto --dist loadscope --cov=. --cov-append tests/large

      - name: Combine coverage
        run: |
          uv run coverage html
          echo "COV_PERCENTAGE=$(uv run coverage report --format=total)" >> "$GITHUB_ENV"

      - uses: actions/upload-artifact@v4
        id: htmlcov-upload-step
        with:
          name: htmlcov
          path: corerl/htmlcov/
          overwrite: true

      - run: |
          echo "ğŸ Test ran with ${{ env.COV_PERCENTAGE }}% coverage ğŸ"
          echo "${{ steps.htmlcov-upload-step.outputs.artifact-url }}"

      - uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            _(execution **${{ github.run_id }}** / attempt **${{ github.run_attempt }}**)_
            ğŸ Test ran with ${{ env.COV_PERCENTAGE }}% coverage ğŸ
            ${{ steps.htmlcov-upload-step.outputs.artifact-url }}
          comment-tag: execution


  docker-build-test:
    needs: [style-n-test]
    uses: ./.github/workflows/reusable-build-docker-image.yml
    secrets: inherit
    with:
      push_to_registry: false
