name: CoreIO Style and Tests
permissions: write-all # Needed to comment coverage% on PR

on:
  pull_request:
    paths:
      - "coreio/**"
      - "libs/**"
      - "config/**"
  merge_group:
    paths:
      - "coreio/**"
      - "libs/**"
      - "config/**"

concurrency:
  group: coreio-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # -----------
  # -- Style --
  # -----------
  coreio-style-n-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: coreio

    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          subrepo: coreio

      - name: set up path
        run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

      # linting
      - uses: astral-sh/ruff-action@v1
        with:
            src: coreio

      - uses: dciborow/action-pylint@0.1.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
          workdir: coreio
          glob_pattern: "src/"

      # type checking
      - uses: jakebailey/pyright-action@v2
        with:
          pylance-version: latest-release
          working-directory: coreio

      - name: Run Pytest
        run: |
          pytest --cov=coreio --cov-report=html --asyncio-mode=auto tests/

      - name: Combine coverage
        run: |
          uv run coverage html
          echo "COV_PERCENTAGE=$(uv run coverage report --format=total)" >> "$GITHUB_ENV"

      - uses: actions/upload-artifact@v4
        id: htmlcov-upload-step
        with:
          name: htmlcov
          path: coreio/htmlcov/
          overwrite: true

      - run: |
          echo "ğŸ CoreIO tests ran with ${{ env.COV_PERCENTAGE }}% coverage ğŸ"
          echo "${{ steps.htmlcov-upload-step.outputs.artifact-url }}"

      - uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            _(execution **${{ github.run_id }}** / attempt **${{ github.run_attempt }}**)_
            ğŸ CoreIO tests ran with ${{ env.COV_PERCENTAGE }}% coverage ğŸ
            ${{ steps.htmlcov-upload-step.outputs.artifact-url }}
          comment-tag: execution-coreio
