name: CoreRL Style and Tests
permissions: write-all # Needed to comment coverage% on PR

on:
  pull_request:
    paths:
      - "coreio/**"
      - "corerl/**"
      - "libs/**"
      - "config/**"

concurrency:
  group: corerl-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # -----------
  # -- Style --
  # -----------
  corerl-style-n-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: corerl

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true

      - name: Setup
        uses: ./.github/actions/setup
        with:
          subrepo: corerl

      - name: set up path
        run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

      # linting
      - uses: astral-sh/ruff-action@v1
        with:
            src: corerl

      - uses: dciborow/action-pylint@0.1.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
          workdir: corerl
          glob_pattern: "corerl/ tests/"

      # type checking
      - uses: jakebailey/pyright-action@v2
        with:
          pylance-version: latest-release
          working-directory: corerl

      # -----------
      # -- Tests --
      # -----------
      - name: Create artifact directory
        run: mkdir -p artifact

      - name: Run Pytest
        run: |
          pytest --cov=. --cov-append tests/small
          pytest --cov=. --cov-append tests/medium
          pytest -n auto --dist loadscope --cov=. --cov-append tests/large
          pytest ../test/test/test_validate_configs.py

      - name: Combine coverage
        run: |
          uv run coverage html
          echo "COV_PERCENTAGE=$(uv run coverage report --format=total)" >> "$GITHUB_ENV"

      # -------------
      # -- Benchmark --
      # -------------
      - name: Run Pytest Benchmark
        run: |
          pytest --benchmark-only --benchmark-json output.json tests/small/

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Python Benchmark with pytest-benchmark
          tool: 'pytest'
          output-file-path: corerl/output.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          alert-threshold: '130%'
          comment-always: true
          summary-always: true
          fail-on-alert: true
          alert-comment-cc-users: '@rlcoretech/rlcore-codeowners @andy-rlcore'

      - uses: actions/upload-artifact@v4
        id: htmlcov-upload-step
        with:
          name: htmlcov
          path: corerl/htmlcov/
          overwrite: true

      - run: |
          echo "ğŸ Test ran with ${{ env.COV_PERCENTAGE }}% coverage ğŸ"
          echo "${{ steps.htmlcov-upload-step.outputs.artifact-url }}"

      - uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            _(execution **${{ github.run_id }}** / attempt **${{ github.run_attempt }}**)_
            ğŸ Test ran with ${{ env.COV_PERCENTAGE }}% coverage ğŸ
            ${{ steps.htmlcov-upload-step.outputs.artifact-url }}
          comment-tag: execution
