name: Style and Tests
permissions: write-all # Needed to comment coverage% on PR

on:
  pull_request:
    paths:
      - "corerl/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # -----------
  # -- Style --
  # -----------
  style-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          subrepo: corerl

      # linting
      - uses: astral-sh/ruff-action@v1
      - uses: dciborow/action-pylint@0.1.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
          glob_pattern: "corerl/ coreio/ test/"

      # type checking
      - uses: jakebailey/pyright-action@v2
        with:
          pylance-version: latest-release
          working-directory: corerl

  # -----------
  # -- Tests --
  # -----------
  small-test:
    needs: [style-check]
    uses: ./.github/workflows/reusable-run-test.yml
    secrets: inherit
    with:
      test-suite: small

  medium-test:
    needs: [style-check]
    uses: ./.github/workflows/reusable-run-test.yml
    secrets: inherit
    with:
      test-suite: medium

  large-test:
    needs: [small-test, medium-test]
    uses: ./.github/workflows/reusable-run-test.yml
    secrets: inherit
    with:
      test-flags: --verbose --dist loadscope
      test-suite: large

  docker-build-test:
    needs: [small-test, medium-test]
    uses: ./.github/workflows/reusable-build-docker-image.yml
    secrets: inherit
    with:
      push_to_registry: false

  combine-coverage:
    needs: [large-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          subrepo: corerl

      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifact
          merge-multiple: true

      - name: Combine coverage and generate reports
        run: |
          cd corerl
          uv run coverage combine artifact/coverage_*
          uv run coverage html
          echo "COV_PERCENTAGE=$(uv run coverage report --format=total)" >> "$GITHUB_ENV"

      - uses: actions/upload-artifact@v4
        id: htmlcov-upload-step
        with:
          name: htmlcov
          path: corerl/htmlcov/
          overwrite: true

      - run: |
          echo "ğŸ Test ran with ${{ env.COV_PERCENTAGE }}% coverage ğŸ"
          echo "${{ steps.htmlcov-upload-step.outputs.artifact-url }}"

      - uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            _(execution **${{ github.run_id }}** / attempt **${{ github.run_attempt }}**)_
            ğŸ Test ran with ${{ env.COV_PERCENTAGE }}% coverage ğŸ
            ${{ steps.htmlcov-upload-step.outputs.artifact-url }}
          comment-tag: execution

      - uses: geekyeggo/delete-artifact@v5
        with:
            name: artifact/*
