name: CoreTelemetry Style and Tests
permissions: write-all # Needed to comment coverage% on PR

on:
  pull_request:
    paths:
      - "coretelemetry/**"
      - "libs/**"
      - "corerl/**"
  merge_group:
    paths:
      - "coretelemetry/**"
      - "libs/**"
      - "corerl/**"

concurrency:
  group: coretelemetry-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # -----------
  # -- Style --
  # -----------
  coretelemetry-style-n-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: coretelemetry

    steps:
      - uses: actions/checkout@v4
      - name: Setup CoreTelemetry
        uses: ./.github/actions/setup
        with:
          subrepo: coretelemetry

      - name: set up path
        run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Pull TimescaleDB Docker image
        if: runner.os == 'Linux'
        run: docker pull timescale/timescaledb:latest-pg17

      # linting
      - uses: astral-sh/ruff-action@v1
        with:
            src: coretelemetry

      # type checking
      - uses: jakebailey/pyright-action@v2
        with:
          pylance-version: latest-release
          working-directory: coretelemetry

      - name: Run Pytest (All tests)
        if: runner.os == 'Linux'
        run: |
          pytest --cov=coretelemetry --cov-report=html tests/

      - name: Run Pytest (System metrics tests only)
        if: runner.os == 'Windows'
        run: |
          pytest --cov=coretelemetry --cov-report=html tests/large/test_system_metrics_api.py

      - name: Combine coverage
        run: |
          uv run coverage html
          echo "COV_PERCENTAGE=$(uv run coverage report --format=total)" >> "$GITHUB_ENV"

      - uses: actions/upload-artifact@v4
        id: htmlcov-upload-step
        with:
          name: htmlcov
          path: coretelemetry/htmlcov/
          overwrite: true

      - run: |
          echo "ğŸ CoreTelemetry tests ran with ${{ env.COV_PERCENTAGE }}% coverage ğŸ"
          echo "${{ steps.htmlcov-upload-step.outputs.artifact-url }}"

      - uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            _(execution **${{ github.run_id }}** / attempt **${{ github.run_attempt }}**)_
            ğŸ CoreTelemetry tests ran with ${{ env.COV_PERCENTAGE }}% coverage ğŸ
            ${{ steps.htmlcov-upload-step.outputs.artifact-url }}
          comment-tag: execution-coretelemetry
