name: CoreDinator Style and Tests
permissions: write-all # Needed to comment coverage% on PR

on:
  pull_request:
    paths:
      - "coredinator/**"
      - "libs/**"
      - "config/**"
  merge_group:
    paths:
      - "coredinator/**"
      - "libs/**"
      - "config/**"

concurrency:
  group: coredinator-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # -----------
  # -- Style --
  # -----------
  coredinator-style-n-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: coredinator

    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          subrepo: coredinator

      - name: set up path
        run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

      # linting
      - uses: astral-sh/ruff-action@v1
        with:
            src: coredinator

      - uses: dciborow/action-pylint@0.1.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
          workdir: coredinator
          glob_pattern: "src/"

      # type checking
      - uses: jakebailey/pyright-action@v2
        with:
          pylance-version: latest-release
          working-directory: coredinator

      - name: Run Pytest
        run: |
          pytest tests/
