name: Libs Style and Tests
permissions: write-all # Needed to comment coverage% on PR

on:
  pull_request:
    paths:
      - "libs/**"
      - ".github/workflows/libs-pr.yml"
  merge_group:
    paths:
      - "libs/**"
      - ".github/workflows/libs-pr.yml"

jobs:
  # -----------
  # -- Style --
  # -----------
  libs-style-n-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        lib: [lib_agent, lib_config, lib_defs, lib_progress, lib_sql, lib_utils, rl_env]
        exclude:
          - os: windows-latest
            lib: lib_sql
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: libs/${{ matrix.lib }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          subrepo: libs/${{ matrix.lib }}

      - uses: astral-sh/ruff-action@v1
        with:
            src: libs/${{ matrix.lib }}

      # type checking
      - uses: jakebailey/pyright-action@v2
        with:
          pylance-version: latest-release
          working-directory: libs/${{ matrix.lib }}

      - name: Run Pytest
        run: |
          pytest tests/
