name: CI on Push to Master

on:
  push:
    branches:
      - master

jobs:
  bump-version:
    if: ${{ !startsWith(github.event.head_commit.message, 'bump:') }}
    runs-on: ubuntu-latest
    name: Release Please

    steps:
    - name: Generate a token
      id: generate-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ vars.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}

    - name: Release Please Action
      id: release
      uses: googleapis/release-please-action@v4
      with:
        token: ${{ steps.generate-token.outputs.token }}
        release-type: python


  generate-docs:
    if: ${{ startsWith(github.event.head_commit.message, 'chore') && contains(github.event.head_commit.message, 'release') }}
    runs-on: ubuntu-latest
    name: Generate Sphinx documentation

    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate-token.outputs.token }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          prune-cache: false
          cache-dependency-glob: "uv.lock"

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_DEPLOY_KEY }}

      - name: Build and Install corerl
        run: |
          uv venv
          uv sync
          uv pip install .

      - name: Build Documentation
        working-directory: ./docs
        run: |
          source ../.venv/bin/activate
          uv pip install sphinx
          uv run sphinx-apidoc -o ./source/api ../corerl
          uv run sphinx-build -M html source build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ steps.generate-token.outputs.token }}
          publish_dir: ./docs/build/html
