name: Run Single Test Group

on:
  workflow_call:
    inputs:
      test-flags:
        required: false
        type: string
      test-suite:
        required: true
        type: string
      upload-coverage:
        required: false
        type: boolean
        default: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # setup the repository
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_DEPLOY_KEY }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          prune-cache: false
          cache-dependency-glob: "uv.lock"

      - run: |
          uv venv
          uv sync

      - name: Install corerl if large
        if: ${{ inputs.test-suite == 'large' || inputs.test-suite == 'behavior' }}
        run: uv pip install .

      - name: Create artifact directory
        if: ${{ inputs.upload-coverage }}
        run: mkdir -p artifact

      - name: Run Pytest
        run: |
          if [ "${{ inputs.upload-coverage }}" = "true" ]; then
            uv run pytest --cov=. ${{ inputs.test-flags }} test/${{ inputs.test-suite }}
          else
            uv run pytest ${{ inputs.test-flags }} test/${{ inputs.test-suite }}
          fi

      - name: Move coverage artifacts
        if: ${{ inputs.upload-coverage }}
        run: mv .coverage artifact/coverage_${{ inputs.test-suite }}

      - name: Upload coverage artifact
        if: ${{ inputs.upload-coverage }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage_${{ inputs.test-suite }}
          path: artifact
