name: Run Single Test Group

on:
  workflow_call:
    inputs:
      test-flags: 
        required: false
        type: string
      test-suite:
        required: true
        type: string

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]

    steps:
      # setup the repository
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_DEPLOY_KEY }}

      - name: Install uv
        uses: astral-sh/setup-uv@v2

      - run: |
          uv venv
          uv pip compile --extra=dev pyproject.toml -o deps.txt
          uv pip sync deps.txt

      - run: mkdir artifact
      - run: uv run pytest --cov=. ${{ inputs.test-flags }} test/${{ inputs.test-suite }} 
      - run: mv .coverage artifact/coverage_${{ inputs.test-suite }}

      - uses: actions/upload-artifact@v4
        with:
          name: coverage_${{ inputs.test-suite }}
          path: artifact
     


