name: Run Single Test Group

on:
  workflow_call:
    inputs:
      test-flags:
        required: false
        type: string
      test-suite:
        required: true
        type: string
      upload-coverage:
        required: false
        type: boolean
        default: true
      runs-on:
        required: false
        type: string
        default: "ubuntu-latest"

env:
  REGISTRY: ghcr.io

jobs:
  test:
    runs-on: ${{ inputs.runs-on }}
    steps:
      # setup the repository
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          prune-cache: false
          cache-dependency-glob: "uv.lock"

      - run: |
          uv venv
          uv sync

      - run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Install corerl if large
        if: ${{ inputs.test-suite == 'large' || inputs.test-suite == 'behavior' }}
        run: uv pip install .

      - name: Login to GHCR registry if large
        if: ${{ inputs.test-suite == 'large' || inputs.test-suite == 'behavior' }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          # username: ${{ vars.TEMP_ALEXW_GHCR_USERNAME }}
          # password: ${{ secrets.TEMP_ALEXW_GHCR_PAT }}

      - name: Create artifact directory
        if: ${{ inputs.upload-coverage }}
        run: mkdir -p artifact

      - name: Run Pytest
        run: |
          if [ "${{ inputs.upload-coverage }}" = "true" ]; then
            uv run pytest -n auto --cov=. ${{ inputs.test-flags }} test/${{ inputs.test-suite }}
          else
            uv run pytest -n auto ${{ inputs.test-flags }} test/${{ inputs.test-suite }}
          fi

      - name: Move coverage artifacts
        if: ${{ inputs.upload-coverage }}
        run: mv .coverage artifact/coverage_${{ inputs.test-suite }}

      - name: Upload coverage artifact
        if: ${{ inputs.upload-coverage }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage_${{ inputs.test-suite }}
          path: artifact
