name: Run Single Test Group

on:
  workflow_call:
    inputs:
      test-flags:
        required: false
        type: string
      test-suite:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # setup the repository
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_DEPLOY_KEY }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"


      - run: |
          uv venv
          uv sync

      - name: Install corerl if large
        if: ${{ inputs.test-suite == 'large' }}
        run: uv pip install .

      - run: mkdir -p artifact
      - run: uv run pytest --cov=. ${{ inputs.test-flags }} test/${{ inputs.test-suite }}
      - run: mv .coverage artifact/coverage_${{ inputs.test-suite }}

      - uses: actions/upload-artifact@v4
        with:
          name: coverage_${{ inputs.test-suite }}
          path: artifact
