name: Test FastAPI Schema Generation

on:
  workflow_call:

jobs:
  fastapi-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
            python-version: 3.12

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          prune-cache: false
          cache-dependency-glob: "uv.lock"

      - name: Install Python dependencies
        run: |
          uv venv
          uv sync
          echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Run web server
        run: | 
          fastapi dev corerl/web/app.py &
          echo $! > corerl_webapp_pid.txt

      - name: Setup Node 
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Validate FastAPI schema
        run: | 
          npx wait-on --timeout 20000 http-get://localhost:8000/ && npx openapi-typescript http://localhost:8000/openapi.json -o schema.ts

      - name: Cleanup web server
        if: always()  # Run even if previous steps fail
        run: |
          if [ -f corerl_webapp_pid.txt ]; then
            kill $(cat corerl_webapp_pid.txt)
          fi
        
