name: Run Single Test Group

on:
  workflow_call:
    inputs:
      test-flags:
        required: false
        type: string
      test-suite:
        required: true
        type: string
      runs-on:
        required: false
        type: string
        default: "ubuntu-latest"

env:
  REGISTRY: ghcr.io

jobs:
  test:
    runs-on: ${{ inputs.runs-on }}
    defaults:
      run:
        working-directory: corerl

    steps:
      - name: Setup
        uses: ./.github/actions/setup
        with:
          subrepo: corerl

      - name: Install corerl if large
        if: ${{ inputs.test-suite == 'large' }}
        run: uv pip install .

      - name: Login to GHCR registry if large
        if: ${{ inputs.test-suite == 'large' }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create artifact directory
        if: ${{ inputs.upload-coverage }}
        run: mkdir -p artifact

      - name: Run Pytest
        run: |
          cd corerl
          uv run pytest -n auto --dist loadscope --cov=. ${{ inputs.test-flags }} test/${{ inputs.test-suite }}

      - name: Move coverage artifacts
        run: mv .coverage artifact/coverage_${{ inputs.test-suite }}

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage_${{ inputs.test-suite }}
          path: corerl/artifact
