name: Behavior Test

on:
  schedule:
    - cron: '0 */2 * * *' # run every 2 hours
  workflow_dispatch:


jobs:
  behavior-test:
    uses: ./.github/workflows/reusable-run-test.yml
    secrets: inherit
    with:
      test-suite: behavior
      upload-coverage: false
      runs-on: threadripper-1
