name: Style and Tests

on: [pull_request]

jobs:
  style-check:
    runs-on: ubuntu-latest
    steps:
      # setup the repository
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
            python-version: 3.12

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_DEPLOY_KEY }}

      - run: |
          uv venv
          uv pip compile --extra=dev pyproject.toml -o deps.txt
          uv pip sync deps.txt

      - run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

      # linting
      - uses: astral-sh/ruff-action@v1

      # type checking
      - uses: jakebailey/pyright-action@v2
        with:
          pylance-version: latest-release

  small-test:
    needs: [style-check]
    uses: ./.github/workflows/reusable-run-test.yml
    secrets: inherit
    with:
      test-suite: -n auto test/small
     # - run: uv run pytest -n auto test/small
     
     #
  medium-test:
    needs: [style-check]
    uses: ./.github/workflows/reusable-run-test.yml
    secrets: inherit
    with:
      test-suite: test/medium
      #- run: uv run pytest test/medium

  large-test:
    needs: [small-test, medium-test]
    uses: ./.github/workflows/reusable-run-test.yml
    secrets: inherit
    with:
      test-suite: test/large
      #- run: uv run pytest test/large
