name: Style and Tests

on: [pull_request]
permissions: write-all # Needed to comment coverage% on PR

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  py-style-check:
    runs-on: ubuntu-latest
    steps:
      # setup the repository
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
            python-version: 3.12

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          prune-cache: false
          cache-dependency-glob: "uv.lock"

      - run: |
          uv venv
          uv sync

      - run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

      # linting
      - uses: astral-sh/ruff-action@v1

      # type checking
      - uses: jakebailey/pyright-action@v2
        with:
          pylance-version: latest-release
