name: Style and Tests

on: [pull_request]
permissions: write-all # Needed to comment coverage% on PR

jobs:
  style-check:
    runs-on: ubuntu-latest
    steps:
      # setup the repository
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
            python-version: 3.12

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_DEPLOY_KEY }}

      - run: |
          uv venv
          uv pip compile --extra=dev pyproject.toml -o deps.txt
          uv pip sync deps.txt

      - run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

      # linting
      - uses: astral-sh/ruff-action@v1

      # type checking
      - uses: jakebailey/pyright-action@v2
        with:
          pylance-version: latest-release

  small-test:
    needs: [style-check]
    uses: ./.github/workflows/reusable-run-test.yml
    secrets: inherit
    with:
      test-flags: -n auto
      test-suite: small
     # - run: uv run pytest -n auto test/small
     
  medium-test:
    needs: [style-check]
    uses: ./.github/workflows/reusable-run-test.yml
    secrets: inherit
    with:
      test-suite: medium
      #- run: uv run pytest test/medium

  large-test:
    needs: [small-test, medium-test]
    uses: ./.github/workflows/reusable-run-test.yml
    secrets: inherit
    with:
      test-suite: large
      #- run: uv run pytest test/large

  combine-coverage:
    needs: [large-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: 3.12

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_DEPLOY_KEY }}

      - run: |
          uv venv
          uv pip compile --extra=dev pyproject.toml -o deps.txt
          uv pip sync deps.txt

      - run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - uses: actions/download-artifact@v4
        with:
          name: coverage_small
          path: artifact

      - uses: actions/download-artifact@v4
        with:
          name: coverage_medium
          path: artifact

      - uses: actions/download-artifact@v4
        with:
          name: coverage_large
          path: artifact

      - run: |
          uv run coverage combine artifact/coverage_small artifact/coverage_medium artifact/coverage_large
          uv run coverage report >> report.txt
          echo "percentage=$(cat report.txt | tail -n 1 | awk {'print $4'})" >> $GITHUB_ENV
          
      - run: echo "ğŸ Test ran with ${{ env.percentage }} coverage ğŸ"

      - uses: thollander/actions-comment-pull-request@v3
        with:
          message: ğŸ Test ran with ${{ env.percentage }} coverage ğŸ

      - uses: geekyeggo/delete-artifact@v5
        with:
            name: artifact/*

