name: Style and Tests

on: [pull_request]
permissions: write-all # Needed to comment coverage% on PR

jobs:
  py-style-check:
    runs-on: ubuntu-latest
    steps:
      # setup the repository
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
            python-version: 3.12

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"


      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_DEPLOY_KEY }}

      - run: |
          uv venv
          uv sync

      - run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

      # linting
      - uses: astral-sh/ruff-action@v1

      # type checking
      - uses: jakebailey/pyright-action@v2
        with:
          pylance-version: latest-release

  web-style-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Lint and Build project
        working-directory: ./client
        run: |
          npm ci
          npm run lint
          npm run build

  small-test:
    needs: [py-style-check]
    uses: ./.github/workflows/reusable-run-test.yml
    secrets: inherit
    with:
      test-flags: -n auto
      test-suite: small
     # - run: uv run pytest -n auto test/small

  medium-test:
    needs: [py-style-check]
    uses: ./.github/workflows/reusable-run-test.yml
    secrets: inherit
    with:
      test-suite: medium
      #- run: uv run pytest test/medium

  large-test:
    needs: [small-test, medium-test]
    uses: ./.github/workflows/reusable-run-test.yml
    secrets: inherit
    with:
      test-suite: large
      #- run: uv run pytest test/large

  combine-coverage:
    needs: [large-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: 3.12

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"


      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_DEPLOY_KEY }}

      - run: |
          uv venv
          uv sync

      - run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifact
          merge-multiple: true

      - name: Combine coverage and generate reports
        run: |
          uv run coverage combine artifact/coverage_*
          uv run coverage html
          echo "COV_PERCENTAGE=$(uv run coverage report --format=total)" >> "$GITHUB_ENV"

      - uses: actions/upload-artifact@v4
        id: htmlcov-upload-step
        with:
          name: htmlcov
          path: htmlcov/
          overwrite: true

      - run: |
          echo "ğŸ Test ran with ${{ env.COV_PERCENTAGE }}% coverage ğŸ"
          echo "${{ steps.htmlcov-upload-step.outputs.artifact-url }}"

      - uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            _(execution **${{ github.run_id }}** / attempt **${{ github.run_attempt }}**)_
            ğŸ Test ran with ${{ env.COV_PERCENTAGE }}% coverage ğŸ
            ${{ steps.htmlcov-upload-step.outputs.artifact-url }}
          comment-tag: execution

      - uses: geekyeggo/delete-artifact@v5
        with:
            name: artifact/*
