name: Style

on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      # setup the repository
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
            python-version: 3.12

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
            enable-cache: true
            cache-dependency-glob: "requirements.txt"

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_DEPLOY_KEY }}

      - run: |
          uv venv
          uv pip install -r requirements.txt

      - run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

      # linting
    #   - uses: chartboost/ruff-action@v1

      # type checking
      - uses: jakebailey/pyright-action@v2
        with:
          pylance-version: latest-release
